// ドリルAI お子さまペルソナ用 クイズデータ
// ことわざ100問 / なぞなぞ100問(ヒント付き) / なかまはずれさがし72問

// ========== ことわざクイズ ==========
// 誤答は「他のことわざの正しい意味」を割り当てているため、選択肢の内容自体は全て正確です。
export interface KotowazaQuestion {
  proverb: string;
  choices: [string, string, string];
  correctIndex: 0 | 1 | 2;
}

export const KOTOWAZA_QUESTIONS: KotowazaQuestion[] = [
  { proverb: "猿も木から落ちる", choices: ["あれこれ 心配するより、やって みると 案外 かんたんな ことが多い", "さわぎが 大きかった わりに、結果は とても 小さい こと", "その道が とくいな人でも、しっぱいする ことがある"], correctIndex: 2 },
  { proverb: "犬も歩けば棒に当たる", choices: ["身近な ことは、かえって 気づきにくい ものだ", "危険を おかさなければ、大きな 成果は 手に 入らない", "出かけると、思いがけない ことに 出あう ことがある"], correctIndex: 2 },
  { proverb: "石の上にも三年", choices: ["力の 強い相手には、逆らわずに 従った方が 得だ", "がまん強く つづければ、いつか うまく いく", "自分に ぴったり 合う場所を 得て、生き生きと 活躍する こと"], correctIndex: 1 },
  { proverb: "塵も積もれば山となる", choices: ["追いつめられた 弱い ものが、思いがけない 強い 反撃を する こと", "自分の 悪い行いの せいで、自分自身が 苦しむ こと", "小さな ことでも、たくさん 集まれば 大きな ものに なる"], correctIndex: 2 },
  { proverb: "急がば回れ", choices: ["何かが 起こる前に、しっかり 準備して おく こと", "とても 用心深く、念には 念を入れて 物事を すすめる こと", "急いでいる時ほど、安全で確かな 方法を えらぶ方が よい"], correctIndex: 2 },
  { proverb: "七転び八起き", choices: ["何度 しっぱいしても、あきらめずに 立ち上がる こと", "昔の ことを よく調べて、そこから 新しい 知恵を 見つける こと", "自分の子ではないように、冷たく あつかう こと"], correctIndex: 0 },
  { proverb: "継続は力なり", choices: ["こつこつ つづける ことが、いちばんの 力に なる", "危険を おかさなければ、大きな 成果は 手に 入らない", "少しばかりの 助けでは、まったく 役に立たない こと"], correctIndex: 0 },
  { proverb: "善は急げ", choices: ["すぐれた 才能が あっても、それを 見つける人が いなければ 活かされない", "その道が とくいな人でも、しっぱいする ことがある", "良いと 思った ことは、すぐに 行動した方が よい"], correctIndex: 2 },
  { proverb: "百聞は一見にしかず", choices: ["人は 若くて 素直な うちに、しっかり きたえた方が良い", "物事に あきっぽくて、長続き しない こと", "何度も話を聞くより、一度 自分の目で 見た方が よく分かる"], correctIndex: 2 },
  { proverb: "失敗は成功のもと", choices: ["すぐれた 才能が あっても、それを 見つける人が いなければ 活かされない", "人は 若くて 素直な うちに、しっかり きたえた方が良い", "しっぱいの 原因を 考える ことで、成功に 近づける"], correctIndex: 2 },
  { proverb: "井の中の蛙大海を知らず", choices: ["せまい 世界しか 知らないと、広い 世の中の ことが 分からない", "一人で 考えるより、みんなで 考えると 良い考えが うかぶ", "口で 説明するより、実際に 行動する方が 大事だ"], correctIndex: 0 },
  { proverb: "弘法にも筆の誤り", choices: ["知らない ことを 聞くのは 一瞬 はずかしいが、聞かないままだと ずっと 損を する", "見た目が 立派な ものが、必ずしも 本当に 価値が あるとは 限らない", "どんなに 上手な人でも、時には まちがえる ことがある"], correctIndex: 2 },
  { proverb: "転ばぬ先の杖", choices: ["人の 好みは いろいろで、他の人には 分からない こともある", "何かが 起こる前に、しっかり 準備して おく こと", "はじめは うそだった ことが、本当に なって しまう こと"], correctIndex: 1 },
  { proverb: "三人寄れば文殊の知恵", choices: ["一人で 考えるより、みんなで 考えると 良い考えが うかぶ", "人の 見ていない ところで、こつこつ がんばって いる人", "見放される ことが あっても、どこかで 助けて くれる人も いる"], correctIndex: 0 },
  { proverb: "好きこそものの上手なれ", choices: ["本当に 大切な子には、あえて 苦労を 経験させた方が 良い", "好きな ことは、自然と 上手に なって いく", "いつも 笑っている 明るい人の ところには、幸せが やって来る"], correctIndex: 1 },
  { proverb: "案ずるより産むが易し", choices: ["同じ 悩みを もつ人 どうしは、たがいに 気持ちが 分かり合える", "何度 しっぱいしても、あきらめずに 立ち上がる こと", "あれこれ 心配するより、やって みると 案外 かんたんな ことが多い"], correctIndex: 2 },
  { proverb: "蓼食う虫も好き好き", choices: ["子は 親に 似た 性質を もつ ものだ", "せまい 世界しか 知らないと、広い 世の中の ことが 分からない", "人の 好みは いろいろで、他の人には 分からない こともある"], correctIndex: 2 },
  { proverb: "木を見て森を見ず", choices: ["小さな ところばかり 気にして、全体を 見わすれて しまう こと", "物事に あきっぽくて、長続き しない こと", "相手からの 強い 言葉や 力を、上手に 受け流す こと"], correctIndex: 0 },
  { proverb: "覆水盆に返らず", choices: ["価値の分かる人でないと、どんなに 良い ものを あげても 意味が ない", "一度 してしまった ことは、もとには もどせない", "時間は 矢のように、あっという間に すぎて いく"], correctIndex: 1 },
  { proverb: "目は口ほどに物を言う", choices: ["力の 強い人の 後ろ盾を 使って、いばって いる 弱い者", "目の表情でも、話す ことと 同じくらい 気持ちが 伝わる", "教わるより、実際に やって 慣れる方が 身に つく"], correctIndex: 1 },
  { proverb: "能ある鷹は爪を隠す", choices: ["見た目が 立派な ものが、必ずしも 本当に 価値が あるとは 限らない", "さわぎが 大きかった わりに、結果は とても 小さい こと", "本当に 実力の ある人は、それを むやみに 見せびらかさない"], correctIndex: 2 },
  { proverb: "光陰矢の如し", choices: ["時間は 矢のように、あっという間に すぎて いく", "最後まで やりとげて、立派な 結果で 終える こと", "本当に 実力の ある人は、それを むやみに 見せびらかさない"], correctIndex: 0 },
  { proverb: "時は金なり", choices: ["さわぎが 大きかった わりに、結果は とても 小さい こと", "時間は お金と 同じくらい 大切な ものだ", "何度も くり返して いる うちに、それが その人の 性格に なる"], correctIndex: 1 },
  { proverb: "類は友を呼ぶ", choices: ["物事が うまく 進む 流れに 乗って、ますます 勢いづく こと", "知らない でいる方が、かえって おだやかで いられる", "気の合う人 どうしは、自然と 集まって 仲良くなる"], correctIndex: 2 },
  { proverb: "良薬は口に苦し", choices: ["ためになる 忠告は、聞くのが つらい ことが多い", "大きい ものは、小さい ものの かわりにも 使える", "急いでいる時ほど、安全で確かな 方法を えらぶ方が よい"], correctIndex: 0 },
  { proverb: "笑う門には福来る", choices: ["いつも 笑っている 明るい人の ところには、幸せが やって来る", "何度も話を聞くより、一度 自分の目で 見た方が よく分かる", "とても 用心深く、念には 念を入れて 物事を すすめる こと"], correctIndex: 0 },
  { proverb: "継子扱い", choices: ["自分の子ではないように、冷たく あつかう こと", "目立って 優れている人は、まわりから 反発されやすい", "とても 用心深く、念には 念を入れて 物事を すすめる こと"], correctIndex: 0 },
  { proverb: "後悔先に立たず", choices: ["相手からの 強い 言葉や 力を、上手に 受け流す こと", "たくさんの意見よりも、力の ある人の 一言で 物事が 決まる こと", "終わった 後で 悔やんでも、前もって 気づく ことは できない"], correctIndex: 2 },
  { proverb: "石橋を叩いて渡る", choices: ["とても 用心深く、念には 念を入れて 物事を すすめる こと", "小さな ところばかり 気にして、全体を 見わすれて しまう こと", "身近な ことは、かえって 気づきにくい ものだ"], correctIndex: 0 },
  { proverb: "虎穴に入らずんば虎子を得ず", choices: ["危険を おかさなければ、大きな 成果は 手に 入らない", "話に 聞いていたのと、実際に 見るのとでは、大きな 差が ある", "思いきって 危険を おかしてこそ、道が 開ける ことも ある"], correctIndex: 0 },
  { proverb: "蛙の子は蛙", choices: ["とても 用心深く、念には 念を入れて 物事を すすめる こと", "欲ばって 二つの ことを 同時に やろうとすると、両方とも うまく いかない", "子は 親に 似た 性質を もつ ものだ"], correctIndex: 2 },
  { proverb: "鬼に金棒", choices: ["どんなに 上手な人でも、時には まちがえる ことがある", "物事は、その道の 専門家に まかせるのが いちばんだ", "もともと 強い ものが、さらに 強い 力を 手に 入れる こと"], correctIndex: 2 },
  { proverb: "灯台下暗し", choices: ["余計な ことに 関わらなければ、面倒な 目には あわない", "目の表情でも、話す ことと 同じくらい 気持ちが 伝わる", "身近な ことは、かえって 気づきにくい ものだ"], correctIndex: 2 },
  { proverb: "苦しい時の神頼み", choices: ["普段は 忘れているのに、困った時だけ 神様に お願いする こと", "何度も話を聞くより、一度 自分の目で 見た方が よく分かる", "強い ものが 弱い ものを 支配する、きびしい 世の中の しくみ"], correctIndex: 0 },
  { proverb: "聞くは一時の恥聞かぬは一生の恥", choices: ["知らない ことを 聞くのは 一瞬 はずかしいが、聞かないままだと ずっと 損を する", "強い ものが 弱い ものを 支配する、きびしい 世の中の しくみ", "最後まで やりとげて、立派な 結果で 終える こと"], correctIndex: 0 },
  { proverb: "習うより慣れよ", choices: ["人の 見ていない ところで、こつこつ がんばって いる人", "教わるより、実際に やって 慣れる方が 身に つく", "出かけると、思いがけない ことに 出あう ことがある"], correctIndex: 1 },
  { proverb: "三日坊主", choices: ["物事に あきっぽくて、長続き しない こと", "はじめは うそだった ことが、本当に なって しまう こと", "物事が うまく 進む 流れに 乗って、ますます 勢いづく こと"], correctIndex: 0 },
  { proverb: "千里の道も一歩から", choices: ["見放される ことが あっても、どこかで 助けて くれる人も いる", "どんなに 大きな ことも、まずは 小さな 一歩から 始まる", "好きな ことは、自然と 上手に なって いく"], correctIndex: 1 },
  { proverb: "捨てる神あれば拾う神あり", choices: ["見放される ことが あっても、どこかで 助けて くれる人も いる", "相手からの 強い 言葉や 力を、上手に 受け流す こと", "その道が とくいな人でも、しっぱいする ことがある"], correctIndex: 0 },
  { proverb: "備えあれば憂いなし", choices: ["新しい場所に行ったら、その土地の やり方に 合わせる方が よい", "すぐれた 才能が あっても、それを 見つける人が いなければ 活かされない", "しっかり 準備して おけば、いざという時に 心配 いらない"], correctIndex: 2 },
  { proverb: "卵を割らずにオムレツは作れない", choices: ["余計な ことに 関わらなければ、面倒な 目には あわない", "何かを 成しとげるには、多少の 犠牲や 苦労が 必要だ", "見放される ことが あっても、どこかで 助けて くれる人も いる"], correctIndex: 1 },
  { proverb: "大は小を兼ねる", choices: ["目の表情でも、話す ことと 同じくらい 気持ちが 伝わる", "価値の分かる人でないと、どんなに 良い ものを あげても 意味が ない", "大きい ものは、小さい ものの かわりにも 使える"], correctIndex: 2 },
  { proverb: "知らぬが仏", choices: ["大きい ものは、小さい ものの かわりにも 使える", "知らない でいる方が、かえって おだやかで いられる", "強い ものが 弱い ものを 支配する、きびしい 世の中の しくみ"], correctIndex: 1 },
  { proverb: "月とすっぽん", choices: ["欲ばって 二つの ことを 同時に やろうとすると、両方とも うまく いかない", "二つの ものが、比べものに ならないほど ちがう こと", "好きな ことは、自然と 上手に なって いく"], correctIndex: 1 },
  { proverb: "鉄は熱いうちに打て", choices: ["良いと 思った ことは、すぐに 行動した方が よい", "人は 若くて 素直な うちに、しっかり きたえた方が良い", "子は 親に 似た 性質を もつ ものだ"], correctIndex: 1 },
  { proverb: "灯火親しむべし", choices: ["自分が した ことの 結果は、自分で 引き受けるべきだ", "秋の 夜長は、明かりの下で 読書するのに ふさわしい", "せまい 世界しか 知らないと、広い 世の中の ことが 分からない"], correctIndex: 1 },
  { proverb: "苦あれば楽あり", choices: ["すぐれた 才能が あっても、それを 見つける人が いなければ 活かされない", "はじめは うそだった ことが、本当に なって しまう こと", "つらい ことの あとには、楽しい ことも やって来る"], correctIndex: 2 },
  { proverb: "二兎を追う者は一兎をも得ず", choices: ["同じ 悩みを もつ人 どうしは、たがいに 気持ちが 分かり合える", "欲ばって 二つの ことを 同時に やろうとすると、両方とも うまく いかない", "楽しい ことの あとには、つらい ことも やって来る"], correctIndex: 1 },
  { proverb: "猫に小判", choices: ["価値の分かる人でないと、どんなに 良い ものを あげても 意味が ない", "普段は 忘れているのに、困った時だけ 神様に お願いする こと", "何度か しっぱいしても、三回目には うまく いく ことが多い"], correctIndex: 0 },
  { proverb: "能書きより実行", choices: ["終わった 後で 悔やんでも、前もって 気づく ことは できない", "口で 説明するより、実際に 行動する方が 大事だ", "その人の うわさを していると、ちょうど その人が やって来る こと"], correctIndex: 1 },
  { proverb: "初心忘るべからず", choices: ["始めた頃の 気持ちを、いつまでも 忘れては いけない", "しっかり 準備して おけば、いざという時に 心配 いらない", "実力の ない人ほど、口だけは 達者な こと"], correctIndex: 0 },
  { proverb: "花より団子", choices: ["人は まわりの 環境に 合わせて、性質が 変わる ものだ", "見た目の美しさより、実際に 役立つ ものを 選ぶ こと", "急に 物事の 本当の姿が 分かるように なる こと"], correctIndex: 1 },
  { proverb: "早起きは三文の徳", choices: ["とても 用心深く、念には 念を入れて 物事を すすめる こと", "もともと 強い ものが、さらに 強い 力を 手に 入れる こと", "早起きすると、ちょっとした 良い ことが ある"], correctIndex: 2 },
  { proverb: "百害あって一利なし", choices: ["がまん強く つづければ、いつか うまく いく", "悪い ことばかりで、良い ことは 一つも ない", "追いつめられた 弱い ものが、思いがけない 強い 反撃を する こと"], correctIndex: 1 },
  { proverb: "負けるが勝ち", choices: ["追いつめられた 弱い ものが、思いがけない 強い 反撃を する こと", "とても 用心深く、念には 念を入れて 物事を すすめる こと", "その場では 負けたように 見えても、それが 結局は 得に なる"], correctIndex: 2 },
  { proverb: "身から出た錆", choices: ["思いがけない ことが 急に 起こって、とても おどろく こと", "余計な ことに 関わらなければ、面倒な 目には あわない", "自分の 悪い行いの せいで、自分自身が 苦しむ こと"], correctIndex: 2 },
  { proverb: "虫の知らせ", choices: ["急いでいる時ほど、安全で確かな 方法を えらぶ方が よい", "何となく 悪い ことが 起こりそうな 予感が する こと", "何度も話を聞くより、一度 自分の目で 見た方が よく分かる"], correctIndex: 1 },
  { proverb: "目から鱗が落ちる", choices: ["急に 物事の 本当の姿が 分かるように なる こと", "子は 親に 似た 性質を もつ ものだ", "何も しなければ、良い 結果も 生まれない"], correctIndex: 0 },
  { proverb: "焼け石に水", choices: ["その人の うわさを していると、ちょうど その人が やって来る こと", "終わった 後で 悔やんでも、前もって 気づく ことは できない", "少しばかりの 助けでは、まったく 役に立たない こと"], correctIndex: 2 },
  { proverb: "柳に風", choices: ["楽しい ことの あとには、つらい ことも やって来る", "相手からの 強い 言葉や 力を、上手に 受け流す こと", "もともと 強い ものが、さらに 強い 力を 手に 入れる こと"], correctIndex: 1 },
  { proverb: "有終の美を飾る", choices: ["最後まで やりとげて、立派な 結果で 終える こと", "同じ 悩みを もつ人 どうしは、たがいに 気持ちが 分かり合える", "何かが 起こる前に、しっかり 準備して おく こと"], correctIndex: 0 },
  { proverb: "楽あれば苦あり", choices: ["早起きすると、ちょっとした 良い ことが ある", "楽しい ことの あとには、つらい ことも やって来る", "その場では 負けたように 見えても、それが 結局は 得に なる"], correctIndex: 1 },
  { proverb: "論より証拠", choices: ["力の 強い相手には、逆らわずに 従った方が 得だ", "あれこれ 話し合うより、証拠を 見せた方が 分かりやすい", "目立って 優れている人は、まわりから 反発されやすい"], correctIndex: 1 },
  { proverb: "我が身をつねって人の痛さを知れ", choices: ["自分が痛い 思いを して初めて、他人の 痛みも 分かる", "良いと 思った ことは、すぐに 行動した方が よい", "見た目の美しさより、実際に 役立つ ものを 選ぶ こと"], correctIndex: 0 },
  { proverb: "渡りに船", choices: ["一人で 考えるより、みんなで 考えると 良い考えが うかぶ", "もともと 強い ものが、さらに 強い 力を 手に 入れる こと", "ちょうど 困っている時に、都合の良い 助けが やって来る こと"], correctIndex: 2 },
  { proverb: "郷に入っては郷に従え", choices: ["急に 物事の 本当の姿が 分かるように なる こと", "はじめは うそだった ことが、本当に なって しまう こと", "新しい場所に行ったら、その土地の やり方に 合わせる方が よい"], correctIndex: 2 },
  { proverb: "蒔かぬ種は生えぬ", choices: ["教わるより、実際に やって 慣れる方が 身に つく", "何も しなければ、良い 結果も 生まれない", "気の合う人 どうしは、自然と 集まって 仲良くなる"], correctIndex: 1 },
  { proverb: "水は方円の器に随う", choices: ["しっぱいの 原因を 考える ことで、成功に 近づける", "人は まわりの 環境に 合わせて、性質が 変わる ものだ", "何となく 悪い ことが 起こりそうな 予感が する こと"], correctIndex: 1 },
  { proverb: "三度目の正直", choices: ["こつこつ つづける ことが、いちばんの 力に なる", "何度か しっぱいしても、三回目には うまく いく ことが多い", "目立って 優れている人は、まわりから 反発されやすい"], correctIndex: 1 },
  { proverb: "嘘から出た実", choices: ["どんなに 上手な人でも、時には まちがえる ことがある", "物事は、その道の 専門家に まかせるのが いちばんだ", "はじめは うそだった ことが、本当に なって しまう こと"], correctIndex: 2 },
  { proverb: "噂をすれば影がさす", choices: ["あれこれ 話し合うより、証拠を 見せた方が 分かりやすい", "その人の うわさを していると、ちょうど その人が やって来る こと", "早起きすると、ちょっとした 良い ことが ある"], correctIndex: 1 },
  { proverb: "縁の下の力持ち", choices: ["良いと 思った ことは、すぐに 行動した方が よい", "見た目の美しさより、実際に 役立つ ものを 選ぶ こと", "人の 見ていない ところで、こつこつ がんばって いる人"], correctIndex: 2 },
  { proverb: "温故知新", choices: ["昔の ことを よく調べて、そこから 新しい 知恵を 見つける こと", "口で 説明するより、実際に 行動する方が 大事だ", "その道が とくいな人でも、しっぱいする ことがある"], correctIndex: 0 },
  { proverb: "火のない所に煙は立たぬ", choices: ["うわさが 立つのには、何かしらの 理由が ある ものだ", "物事に あきっぽくて、長続き しない こと", "その場では 負けたように 見えても、それが 結局は 得に なる"], correctIndex: 0 },
  { proverb: "かわいい子には旅をさせよ", choices: ["ためになる 忠告は、聞くのが つらい ことが多い", "本当に 大切な子には、あえて 苦労を 経験させた方が 良い", "目の表情でも、話す ことと 同じくらい 気持ちが 伝わる"], correctIndex: 1 },
  { proverb: "聞いて極楽見て地獄", choices: ["良いと 思った ことは、すぐに 行動した方が よい", "話に 聞いていたのと、実際に 見るのとでは、大きな 差が ある", "本当に 大切な子には、あえて 苦労を 経験させた方が 良い"], correctIndex: 1 },
  { proverb: "窮鼠猫を噛む", choices: ["思いきって 危険を おかしてこそ、道が 開ける ことも ある", "何かを 成しとげるには、多少の 犠牲や 苦労が 必要だ", "追いつめられた 弱い ものが、思いがけない 強い 反撃を する こと"], correctIndex: 2 },
  { proverb: "弱肉強食", choices: ["本当に 大切な子には、あえて 苦労を 経験させた方が 良い", "強い ものが 弱い ものを 支配する、きびしい 世の中の しくみ", "楽しい ことの あとには、つらい ことも やって来る"], correctIndex: 1 },
  { proverb: "光り輝くもの必ずしも金ならず", choices: ["良いと 思った ことは、すぐに 行動した方が よい", "新しい場所に行ったら、その土地の やり方に 合わせる方が よい", "見た目が 立派な ものが、必ずしも 本当に 価値が あるとは 限らない"], correctIndex: 2 },
  { proverb: "好きな道には金を惜しまず", choices: ["何度も話を聞くより、一度 自分の目で 見た方が よく分かる", "追いつめられた 弱い ものが、思いがけない 強い 反撃を する こと", "自分の 大好きな ことには、お金を かけて しまう ものだ"], correctIndex: 2 },
  { proverb: "転石苔むさず", choices: ["見た目の美しさより、実際に 役立つ ものを 選ぶ こと", "落ち着かず 動き回っている人は、なかなか 実力や 財産が つかない", "あれこれ 心配するより、やって みると 案外 かんたんな ことが多い"], correctIndex: 1 },
  { proverb: "触らぬ神に祟りなし", choices: ["本当に 大切な子には、あえて 苦労を 経験させた方が 良い", "追いつめられた 弱い ものが、思いがけない 強い 反撃を する こと", "余計な ことに 関わらなければ、面倒な 目には あわない"], correctIndex: 2 },
  { proverb: "大山鳴動して鼠一匹", choices: ["さわぎが 大きかった わりに、結果は とても 小さい こと", "悪い ことばかりで、良い ことは 一つも ない", "同じ 悩みを もつ人 どうしは、たがいに 気持ちが 分かり合える"], correctIndex: 0 },
  { proverb: "鶴の一声", choices: ["たくさんの意見よりも、力の ある人の 一言で 物事が 決まる こと", "普段は 忘れているのに、困った時だけ 神様に お願いする こと", "自分の子ではないように、冷たく あつかう こと"], correctIndex: 0 },
  { proverb: "出る杭は打たれる", choices: ["普段は 忘れているのに、困った時だけ 神様に お願いする こと", "目立って 優れている人は、まわりから 反発されやすい", "子は 親に 似た 性質を もつ ものだ"], correctIndex: 1 },
  { proverb: "同病相憐れむ", choices: ["同じ 悩みを もつ人 どうしは、たがいに 気持ちが 分かり合える", "さわぎが 大きかった わりに、結果は とても 小さい こと", "力の 強い人の 後ろ盾を 使って、いばって いる 弱い者"], correctIndex: 0 },
  { proverb: "虎の威を借る狐", choices: ["何かを 成しとげるには、多少の 犠牲や 苦労が 必要だ", "物事は、その道の 専門家に まかせるのが いちばんだ", "力の 強い人の 後ろ盾を 使って、いばって いる 弱い者"], correctIndex: 2 },
  { proverb: "長いものには巻かれろ", choices: ["少しばかりの 助けでは、まったく 役に立たない こと", "力の 強い相手には、逆らわずに 従った方が 得だ", "自分の 大好きな ことには、お金を かけて しまう ものだ"], correctIndex: 1 },
  { proverb: "流れに棹さす", choices: ["何度か しっぱいしても、三回目には うまく いく ことが多い", "しっぱいの 原因を 考える ことで、成功に 近づける", "物事が うまく 進む 流れに 乗って、ますます 勢いづく こと"], correctIndex: 2 },
  { proverb: "習い性となる", choices: ["人の 好みは いろいろで、他の人には 分からない こともある", "人は 若くて 素直な うちに、しっかり きたえた方が良い", "何度も くり返して いる うちに、それが その人の 性格に なる"], correctIndex: 2 },
  { proverb: "二階から目薬", choices: ["物事に あきっぽくて、長続き しない こと", "欲ばって 二つの ことを 同時に やろうとすると、両方とも うまく いかない", "回り道すぎて、少しも 効果が ない こと"], correctIndex: 2 },
  { proverb: "寝耳に水", choices: ["回り道すぎて、少しも 効果が ない こと", "思いがけない ことが 急に 起こって、とても おどろく こと", "はじめは うそだった ことが、本当に なって しまう こと"], correctIndex: 1 },
  { proverb: "能無しの口叩き", choices: ["その人の うわさを していると、ちょうど その人が やって来る こと", "実力の ない人ほど、口だけは 達者な こと", "同じ 悩みを もつ人 どうしは、たがいに 気持ちが 分かり合える"], correctIndex: 1 },
  { proverb: "覆いを取れば正体が知れる", choices: ["小さな ところばかり 気にして、全体を 見わすれて しまう こと", "普段は 忘れているのに、困った時だけ 神様に お願いする こと", "かくして いた ことも、いつか 本当の 姿が 分かって しまう"], correctIndex: 2 },
  { proverb: "蒔いた種は自分で刈れ", choices: ["その人の うわさを していると、ちょうど その人が やって来る こと", "思いきって 危険を おかしてこそ、道が 開ける ことも ある", "自分が した ことの 結果は、自分で 引き受けるべきだ"], correctIndex: 2 },
  { proverb: "水を得た魚のよう", choices: ["強い ものが 弱い ものを 支配する、きびしい 世の中の しくみ", "物事に あきっぽくて、長続き しない こと", "自分に ぴったり 合う場所を 得て、生き生きと 活躍する こと"], correctIndex: 2 },
  { proverb: "身を捨ててこそ浮かぶ瀬もあれ", choices: ["思いきって 危険を おかしてこそ、道が 開ける ことも ある", "自分の子ではないように、冷たく あつかう こと", "力の 強い相手には、逆らわずに 従った方が 得だ"], correctIndex: 0 },
  { proverb: "餅は餅屋", choices: ["あれこれ 話し合うより、証拠を 見せた方が 分かりやすい", "物事は、その道の 専門家に まかせるのが いちばんだ", "ちょうど 困っている時に、都合の良い 助けが やって来る こと"], correctIndex: 1 },
  { proverb: "千里の馬も伯楽に会わず", choices: ["すぐれた 才能が あっても、それを 見つける人が いなければ 活かされない", "余計な ことに 関わらなければ、面倒な 目には あわない", "どんなに 上手な人でも、時には まちがえる ことがある"], correctIndex: 0 },
  { proverb: "雨降って地固まる", choices: ["その道が とくいな人でも、しっぱいする ことがある", "もめごとの あとの方が、かえって 物事が 落ち着く ことが 多い", "何度 しっぱいしても、あきらめずに 立ち上がる こと"], correctIndex: 1 },
];

// ========== なかまはずれさがし(4〜6歳向け) ==========
// 4つの絵のうち、oddIndex 番目だけが違う仲間。文字が読めなくても絵と音声で遊べる。
// name は音声読み上げ用のよみがな。
export interface NakamaItem {
  emoji: string;
  name: string;
}

export interface NakamaQuestion {
  items: [NakamaItem, NakamaItem, NakamaItem, NakamaItem];
  oddIndex: 0 | 1 | 2 | 3;
  mainCategory: string;
  oddCategory: string;
}

export const NAKAMA_QUESTIONS: NakamaQuestion[] = [
  { items: [{ emoji: "🥝", name: "きうい" }, { emoji: "🍒", name: "さくらんぼ" }, { emoji: "🐘", name: "ぞう" }, { emoji: "🍉", name: "すいか" }], oddIndex: 2, mainCategory: "くだもの", oddCategory: "どうぶつ" },
  { items: [{ emoji: "🍅", name: "とまと" }, { emoji: "🎃", name: "かぼちゃ" }, { emoji: "⚽", name: "さっかーぼーる" }, { emoji: "🧅", name: "たまねぎ" }], oddIndex: 2, mainCategory: "やさい", oddCategory: "スポーツ" },
  { items: [{ emoji: "🚂", name: "きしゃ" }, { emoji: "🚁", name: "へりこぷたー" }, { emoji: "🥬", name: "きゃべつ" }, { emoji: "🚗", name: "じどうしゃ" }], oddIndex: 2, mainCategory: "のりもの", oddCategory: "やさい" },
  { items: [{ emoji: "☁️", name: "くも" }, { emoji: "🐯", name: "とら" }, { emoji: "🦁", name: "らいおん" }, { emoji: "🐷", name: "ぶた" }], oddIndex: 0, mainCategory: "どうぶつ", oddCategory: "てんき・そら" },
  { items: [{ emoji: "🖍️", name: "くれよん" }, { emoji: "🦋", name: "ちょうちょ" }, { emoji: "🦗", name: "こおろぎ" }, { emoji: "🐞", name: "てんとうむし" }], oddIndex: 0, mainCategory: "むし", oddCategory: "ぶんぼうぐ" },
  { items: [{ emoji: "🐠", name: "ねったいぎょ" }, { emoji: "🦐", name: "えび" }, { emoji: "🐡", name: "ふぐ" }, { emoji: "🌙", name: "つき" }], oddIndex: 3, mainCategory: "うみのいきもの", oddCategory: "てんき・そら" },
  { items: [{ emoji: "🦅", name: "わし" }, { emoji: "🦢", name: "はくちょう" }, { emoji: "🦆", name: "あひる" }, { emoji: "🎾", name: "てにすのぼーる" }], oddIndex: 3, mainCategory: "とり", oddCategory: "スポーツ" },
  { items: [{ emoji: "🦈", name: "さめ" }, { emoji: "🍮", name: "ぷりん" }, { emoji: "🍰", name: "けーき" }, { emoji: "🍪", name: "くっきー" }], oddIndex: 0, mainCategory: "おかし", oddCategory: "うみのいきもの" },
  { items: [{ emoji: "✂️", name: "はさみ" }, { emoji: "📏", name: "ものさし" }, { emoji: "📕", name: "ほん" }, { emoji: "☁️", name: "くも" }], oddIndex: 3, mainCategory: "ぶんぼうぐ", oddCategory: "てんき・そら" },
  { items: [{ emoji: "🌈", name: "にじ" }, { emoji: "⛄", name: "ゆきだるま" }, { emoji: "⭐", name: "ほし" }, { emoji: "🖍️", name: "くれよん" }], oddIndex: 3, mainCategory: "てんき・そら", oddCategory: "ぶんぼうぐ" },
  { items: [{ emoji: "🎺", name: "とらんぺっと" }, { emoji: "🐜", name: "あり" }, { emoji: "🎸", name: "ぎたー" }, { emoji: "🪕", name: "ばんじょー" }], oddIndex: 1, mainCategory: "がっき", oddCategory: "むし" },
  { items: [{ emoji: "⚾", name: "やきゅうのぼーる" }, { emoji: "🏀", name: "ばすけっとぼーる" }, { emoji: "🏓", name: "ぴんぽん" }, { emoji: "⭐", name: "ほし" }], oddIndex: 3, mainCategory: "スポーツ", oddCategory: "てんき・そら" },
  { items: [{ emoji: "🍊", name: "みかん" }, { emoji: "🍎", name: "りんご" }, { emoji: "🍒", name: "さくらんぼ" }, { emoji: "⚡", name: "かみなり" }], oddIndex: 3, mainCategory: "くだもの", oddCategory: "てんき・そら" },
  { items: [{ emoji: "🍅", name: "とまと" }, { emoji: "🧅", name: "たまねぎ" }, { emoji: "🍆", name: "なす" }, { emoji: "🎾", name: "てにすのぼーる" }], oddIndex: 3, mainCategory: "やさい", oddCategory: "スポーツ" },
  { items: [{ emoji: "🚑", name: "きゅうきゅうしゃ" }, { emoji: "✈️", name: "ひこうき" }, { emoji: "🌙", name: "つき" }, { emoji: "🚌", name: "ばす" }], oddIndex: 2, mainCategory: "のりもの", oddCategory: "てんき・そら" },
  { items: [{ emoji: "🐮", name: "うし" }, { emoji: "🎃", name: "かぼちゃ" }, { emoji: "🐵", name: "さる" }, { emoji: "🐶", name: "いぬ" }], oddIndex: 1, mainCategory: "どうぶつ", oddCategory: "やさい" },
  { items: [{ emoji: "🦗", name: "こおろぎ" }, { emoji: "🍩", name: "どーなつ" }, { emoji: "🐜", name: "あり" }, { emoji: "🦂", name: "さそり" }], oddIndex: 1, mainCategory: "むし", oddCategory: "おかし" },
  { items: [{ emoji: "🐡", name: "ふぐ" }, { emoji: "🐚", name: "かい" }, { emoji: "🐬", name: "いるか" }, { emoji: "⛄", name: "ゆきだるま" }], oddIndex: 3, mainCategory: "うみのいきもの", oddCategory: "てんき・そら" },
  { items: [{ emoji: "🐔", name: "にわとり" }, { emoji: "✂️", name: "はさみ" }, { emoji: "🐧", name: "ぺんぎん" }, { emoji: "🦉", name: "ふくろう" }], oddIndex: 1, mainCategory: "とり", oddCategory: "ぶんぼうぐ" },
  { items: [{ emoji: "🍭", name: "あめ" }, { emoji: "🍮", name: "ぷりん" }, { emoji: "🏐", name: "ばれーぼーる" }, { emoji: "🍫", name: "ちょこれーと" }], oddIndex: 2, mainCategory: "おかし", oddCategory: "スポーツ" },
  { items: [{ emoji: "✏️", name: "えんぴつ" }, { emoji: "🥬", name: "きゃべつ" }, { emoji: "🖌️", name: "ふで" }, { emoji: "📎", name: "くりっぷ" }], oddIndex: 1, mainCategory: "ぶんぼうぐ", oddCategory: "やさい" },
  { items: [{ emoji: "⚡", name: "かみなり" }, { emoji: "⭐", name: "ほし" }, { emoji: "🌧️", name: "あめ" }, { emoji: "🖍️", name: "くれよん" }], oddIndex: 3, mainCategory: "てんき・そら", oddCategory: "ぶんぼうぐ" },
  { items: [{ emoji: "🎻", name: "ばいおりん" }, { emoji: "🥁", name: "たいこ" }, { emoji: "🌧️", name: "あめ" }, { emoji: "🎹", name: "ぴあの" }], oddIndex: 2, mainCategory: "がっき", oddCategory: "てんき・そら" },
  { items: [{ emoji: "🏀", name: "ばすけっとぼーる" }, { emoji: "⚽", name: "さっかーぼーる" }, { emoji: "🌙", name: "つき" }, { emoji: "🏐", name: "ばれーぼーる" }], oddIndex: 2, mainCategory: "スポーツ", oddCategory: "てんき・そら" },
  { items: [{ emoji: "🍎", name: "りんご" }, { emoji: "🍍", name: "ぱいなっぷる" }, { emoji: "🚂", name: "きしゃ" }, { emoji: "🍒", name: "さくらんぼ" }], oddIndex: 2, mainCategory: "くだもの", oddCategory: "のりもの" },
  { items: [{ emoji: "🦗", name: "こおろぎ" }, { emoji: "🥔", name: "じゃがいも" }, { emoji: "🎃", name: "かぼちゃ" }, { emoji: "🌽", name: "とうもろこし" }], oddIndex: 0, mainCategory: "やさい", oddCategory: "むし" },
  { items: [{ emoji: "🍮", name: "ぷりん" }, { emoji: "🚲", name: "じてんしゃ" }, { emoji: "🚀", name: "ろけっと" }, { emoji: "🚒", name: "しょうぼうしゃ" }], oddIndex: 0, mainCategory: "のりもの", oddCategory: "おかし" },
  { items: [{ emoji: "🦁", name: "らいおん" }, { emoji: "🐼", name: "ぱんだ" }, { emoji: "🐰", name: "うさぎ" }, { emoji: "🚂", name: "きしゃ" }], oddIndex: 3, mainCategory: "どうぶつ", oddCategory: "のりもの" },
  { items: [{ emoji: "🦗", name: "こおろぎ" }, { emoji: "🐝", name: "はち" }, { emoji: "🦋", name: "ちょうちょ" }, { emoji: "🎾", name: "てにすのぼーる" }], oddIndex: 3, mainCategory: "むし", oddCategory: "スポーツ" },
  { items: [{ emoji: "🐳", name: "くじら" }, { emoji: "🐚", name: "かい" }, { emoji: "🐟", name: "さかな" }, { emoji: "🍅", name: "とまと" }], oddIndex: 3, mainCategory: "うみのいきもの", oddCategory: "やさい" },
  { items: [{ emoji: "🐦", name: "とり" }, { emoji: "🦆", name: "あひる" }, { emoji: "🥁", name: "たいこ" }, { emoji: "🦜", name: "おうむ" }], oddIndex: 2, mainCategory: "とり", oddCategory: "がっき" },
  { items: [{ emoji: "🍩", name: "どーなつ" }, { emoji: "🦒", name: "きりん" }, { emoji: "🍮", name: "ぷりん" }, { emoji: "🍦", name: "そふとくりーむ" }], oddIndex: 1, mainCategory: "おかし", oddCategory: "どうぶつ" },
  { items: [{ emoji: "✏️", name: "えんぴつ" }, { emoji: "📎", name: "くりっぷ" }, { emoji: "✂️", name: "はさみ" }, { emoji: "🐠", name: "ねったいぎょ" }], oddIndex: 3, mainCategory: "ぶんぼうぐ", oddCategory: "うみのいきもの" },
  { items: [{ emoji: "🏓", name: "ぴんぽん" }, { emoji: "☀️", name: "たいよう" }, { emoji: "🌧️", name: "あめ" }, { emoji: "🌙", name: "つき" }], oddIndex: 0, mainCategory: "てんき・そら", oddCategory: "スポーツ" },
  { items: [{ emoji: "🦅", name: "わし" }, { emoji: "🎹", name: "ぴあの" }, { emoji: "🎺", name: "とらんぺっと" }, { emoji: "🎸", name: "ぎたー" }], oddIndex: 0, mainCategory: "がっき", oddCategory: "とり" },
  { items: [{ emoji: "🏓", name: "ぴんぽん" }, { emoji: "🎾", name: "てにすのぼーる" }, { emoji: "⚽", name: "さっかーぼーる" }, { emoji: "🦀", name: "かに" }], oddIndex: 3, mainCategory: "スポーツ", oddCategory: "うみのいきもの" },
  { items: [{ emoji: "🐱", name: "ねこ" }, { emoji: "🍎", name: "りんご" }, { emoji: "🍊", name: "みかん" }, { emoji: "🍓", name: "いちご" }], oddIndex: 0, mainCategory: "くだもの", oddCategory: "どうぶつ" },
  { items: [{ emoji: "🧅", name: "たまねぎ" }, { emoji: "📒", name: "のーと" }, { emoji: "🌽", name: "とうもろこし" }, { emoji: "🥕", name: "にんじん" }], oddIndex: 1, mainCategory: "やさい", oddCategory: "ぶんぼうぐ" },
  { items: [{ emoji: "🚁", name: "へりこぷたー" }, { emoji: "✈️", name: "ひこうき" }, { emoji: "🚌", name: "ばす" }, { emoji: "🍩", name: "どーなつ" }], oddIndex: 3, mainCategory: "のりもの", oddCategory: "おかし" },
  { items: [{ emoji: "🍊", name: "みかん" }, { emoji: "🦒", name: "きりん" }, { emoji: "🐯", name: "とら" }, { emoji: "🐶", name: "いぬ" }], oddIndex: 0, mainCategory: "どうぶつ", oddCategory: "くだもの" },
  { items: [{ emoji: "🐞", name: "てんとうむし" }, { emoji: "✏️", name: "えんぴつ" }, { emoji: "🦂", name: "さそり" }, { emoji: "🐝", name: "はち" }], oddIndex: 1, mainCategory: "むし", oddCategory: "ぶんぼうぐ" },
  { items: [{ emoji: "🐬", name: "いるか" }, { emoji: "🥕", name: "にんじん" }, { emoji: "🦈", name: "さめ" }, { emoji: "🐠", name: "ねったいぎょ" }], oddIndex: 1, mainCategory: "うみのいきもの", oddCategory: "やさい" },
  { items: [{ emoji: "🐦", name: "とり" }, { emoji: "✂️", name: "はさみ" }, { emoji: "🦉", name: "ふくろう" }, { emoji: "🦅", name: "わし" }], oddIndex: 1, mainCategory: "とり", oddCategory: "ぶんぼうぐ" },
  { items: [{ emoji: "⛄", name: "ゆきだるま" }, { emoji: "🍦", name: "そふとくりーむ" }, { emoji: "🍫", name: "ちょこれーと" }, { emoji: "🍮", name: "ぷりん" }], oddIndex: 0, mainCategory: "おかし", oddCategory: "てんき・そら" },
  { items: [{ emoji: "📕", name: "ほん" }, { emoji: "🖌️", name: "ふで" }, { emoji: "🍫", name: "ちょこれーと" }, { emoji: "🖍️", name: "くれよん" }], oddIndex: 2, mainCategory: "ぶんぼうぐ", oddCategory: "おかし" },
  { items: [{ emoji: "📒", name: "のーと" }, { emoji: "⭐", name: "ほし" }, { emoji: "🌧️", name: "あめ" }, { emoji: "⛄", name: "ゆきだるま" }], oddIndex: 0, mainCategory: "てんき・そら", oddCategory: "ぶんぼうぐ" },
  { items: [{ emoji: "🎸", name: "ぎたー" }, { emoji: "🦁", name: "らいおん" }, { emoji: "🎹", name: "ぴあの" }, { emoji: "🎺", name: "とらんぺっと" }], oddIndex: 1, mainCategory: "がっき", oddCategory: "どうぶつ" },
  { items: [{ emoji: "🎾", name: "てにすのぼーる" }, { emoji: "🐛", name: "いもむし" }, { emoji: "🏀", name: "ばすけっとぼーる" }, { emoji: "⚽", name: "さっかーぼーる" }], oddIndex: 1, mainCategory: "スポーツ", oddCategory: "むし" },
  { items: [{ emoji: "🍓", name: "いちご" }, { emoji: "🍊", name: "みかん" }, { emoji: "📒", name: "のーと" }, { emoji: "🍒", name: "さくらんぼ" }], oddIndex: 2, mainCategory: "くだもの", oddCategory: "ぶんぼうぐ" },
  { items: [{ emoji: "🎃", name: "かぼちゃ" }, { emoji: "🪕", name: "ばんじょー" }, { emoji: "🧅", name: "たまねぎ" }, { emoji: "🥔", name: "じゃがいも" }], oddIndex: 1, mainCategory: "やさい", oddCategory: "がっき" },
  { items: [{ emoji: "🚂", name: "きしゃ" }, { emoji: "🚗", name: "じどうしゃ" }, { emoji: "🚕", name: "たくしー" }, { emoji: "🧁", name: "かっぷけーき" }], oddIndex: 3, mainCategory: "のりもの", oddCategory: "おかし" },
  { items: [{ emoji: "🍆", name: "なす" }, { emoji: "🐼", name: "ぱんだ" }, { emoji: "🐷", name: "ぶた" }, { emoji: "🦁", name: "らいおん" }], oddIndex: 0, mainCategory: "どうぶつ", oddCategory: "やさい" },
  { items: [{ emoji: "🍊", name: "みかん" }, { emoji: "🦂", name: "さそり" }, { emoji: "🦋", name: "ちょうちょ" }, { emoji: "🦗", name: "こおろぎ" }], oddIndex: 0, mainCategory: "むし", oddCategory: "くだもの" },
  { items: [{ emoji: "🦈", name: "さめ" }, { emoji: "🐚", name: "かい" }, { emoji: "🐠", name: "ねったいぎょ" }, { emoji: "🚕", name: "たくしー" }], oddIndex: 3, mainCategory: "うみのいきもの", oddCategory: "のりもの" },
  { items: [{ emoji: "🐦", name: "とり" }, { emoji: "🦅", name: "わし" }, { emoji: "📏", name: "ものさし" }, { emoji: "🐧", name: "ぺんぎん" }], oddIndex: 2, mainCategory: "とり", oddCategory: "ぶんぼうぐ" },
  { items: [{ emoji: "🎾", name: "てにすのぼーる" }, { emoji: "🍩", name: "どーなつ" }, { emoji: "🍭", name: "あめ" }, { emoji: "🍪", name: "くっきー" }], oddIndex: 0, mainCategory: "おかし", oddCategory: "スポーツ" },
  { items: [{ emoji: "🖍️", name: "くれよん" }, { emoji: "✂️", name: "はさみ" }, { emoji: "🌧️", name: "あめ" }, { emoji: "🖌️", name: "ふで" }], oddIndex: 2, mainCategory: "ぶんぼうぐ", oddCategory: "てんき・そら" },
  { items: [{ emoji: "☀️", name: "たいよう" }, { emoji: "📕", name: "ほん" }, { emoji: "☁️", name: "くも" }, { emoji: "🌧️", name: "あめ" }], oddIndex: 1, mainCategory: "てんき・そら", oddCategory: "ぶんぼうぐ" },
  { items: [{ emoji: "🎹", name: "ぴあの" }, { emoji: "🦉", name: "ふくろう" }, { emoji: "🎺", name: "とらんぺっと" }, { emoji: "🥁", name: "たいこ" }], oddIndex: 1, mainCategory: "がっき", oddCategory: "とり" },
  { items: [{ emoji: "🏓", name: "ぴんぽん" }, { emoji: "⚽", name: "さっかーぼーる" }, { emoji: "🌈", name: "にじ" }, { emoji: "🎾", name: "てにすのぼーる" }], oddIndex: 2, mainCategory: "スポーツ", oddCategory: "てんき・そら" },
  { items: [{ emoji: "🍐", name: "なし" }, { emoji: "🍍", name: "ぱいなっぷる" }, { emoji: "📏", name: "ものさし" }, { emoji: "🍌", name: "ばなな" }], oddIndex: 2, mainCategory: "くだもの", oddCategory: "ぶんぼうぐ" },
  { items: [{ emoji: "🍅", name: "とまと" }, { emoji: "🥔", name: "じゃがいも" }, { emoji: "🎃", name: "かぼちゃ" }, { emoji: "📕", name: "ほん" }], oddIndex: 3, mainCategory: "やさい", oddCategory: "ぶんぼうぐ" },
  { items: [{ emoji: "🚕", name: "たくしー" }, { emoji: "🦗", name: "こおろぎ" }, { emoji: "✈️", name: "ひこうき" }, { emoji: "🚀", name: "ろけっと" }], oddIndex: 1, mainCategory: "のりもの", oddCategory: "むし" },
  { items: [{ emoji: "🦁", name: "らいおん" }, { emoji: "🎻", name: "ばいおりん" }, { emoji: "🐻", name: "くま" }, { emoji: "🐰", name: "うさぎ" }], oddIndex: 1, mainCategory: "どうぶつ", oddCategory: "がっき" },
  { items: [{ emoji: "🦂", name: "さそり" }, { emoji: "🐞", name: "てんとうむし" }, { emoji: "⛄", name: "ゆきだるま" }, { emoji: "🦗", name: "こおろぎ" }], oddIndex: 2, mainCategory: "むし", oddCategory: "てんき・そら" },
  { items: [{ emoji: "🦀", name: "かに" }, { emoji: "🎺", name: "とらんぺっと" }, { emoji: "🐙", name: "たこ" }, { emoji: "🐠", name: "ねったいぎょ" }], oddIndex: 1, mainCategory: "うみのいきもの", oddCategory: "がっき" },
  { items: [{ emoji: "🚕", name: "たくしー" }, { emoji: "🦆", name: "あひる" }, { emoji: "🐔", name: "にわとり" }, { emoji: "🦅", name: "わし" }], oddIndex: 0, mainCategory: "とり", oddCategory: "のりもの" },
  { items: [{ emoji: "🍮", name: "ぷりん" }, { emoji: "🍫", name: "ちょこれーと" }, { emoji: "🎹", name: "ぴあの" }, { emoji: "🍰", name: "けーき" }], oddIndex: 2, mainCategory: "おかし", oddCategory: "がっき" },
  { items: [{ emoji: "📕", name: "ほん" }, { emoji: "📏", name: "ものさし" }, { emoji: "📒", name: "のーと" }, { emoji: "🦉", name: "ふくろう" }], oddIndex: 3, mainCategory: "ぶんぼうぐ", oddCategory: "とり" },
  { items: [{ emoji: "🌙", name: "つき" }, { emoji: "⚡", name: "かみなり" }, { emoji: "🍎", name: "りんご" }, { emoji: "☁️", name: "くも" }], oddIndex: 2, mainCategory: "てんき・そら", oddCategory: "くだもの" },
  { items: [{ emoji: "🎻", name: "ばいおりん" }, { emoji: "🎺", name: "とらんぺっと" }, { emoji: "🎹", name: "ぴあの" }, { emoji: "🐮", name: "うし" }], oddIndex: 3, mainCategory: "がっき", oddCategory: "どうぶつ" },
  { items: [{ emoji: "⚾", name: "やきゅうのぼーる" }, { emoji: "⚽", name: "さっかーぼーる" }, { emoji: "🍉", name: "すいか" }, { emoji: "🏀", name: "ばすけっとぼーる" }], oddIndex: 2, mainCategory: "スポーツ", oddCategory: "くだもの" },
];
