// なぞなぞ 200問(ユーザー提供PDF「子ども向け なぞなぞ200」より)
// 10ジャンル × 20問。no はPDFの問題番号と一致します。
//
// acceptableAnswers: 正解として認める表記(漢字・カタカナ・ひらがな・数字)。
//   判定は「入力」と「acceptableAnswersの各要素」の両方を同じ normalizeAnswer() に
//   通してから比較すること。カタカナ→ひらがな変換は必須。
//   ※しりとり用の KANA_NORMALIZE(濁点を清音に潰す処理)をここで使ってはいけない。
//
// openEnded: true の3問は「なぜ?」系で答えが文章のため、入力の一致判定ができない。
//   入力欄・マイクを出さず「こたえを みる」ボタンだけを表示すること。
//
// hint: 答えそのものは含まない(頭文字と文字数だけ)。
// note: 正解を表示するときに一緒に見せる かんたんな解説。
export interface NazonazoQuestion {
  no: number;
  genre: string;
  question: string;
  acceptableAnswers: string[];
  hint: string;
  displayAnswer: string;
  note: string;
  openEnded: boolean;
}

export const NAZONAZO_QUESTIONS: NazonazoQuestion[] = [
  { no: 1, genre: "食べもの", question: "赤や緑の服を着ていて、切ると白い。まんなかに小さな種がある果物は?", acceptableAnswers: ["りんご"], hint: "「り」から はじまる 3もじの ことばだよ", displayAnswer: "りんご", note: "皮の色はいろいろでも、中は白っぽい果物です。", openEnded: false },
  { no: 2, genre: "食べもの", question: "黄色い服をむいてから食べる、細長くて甘い果物は?", acceptableAnswers: ["ばなな", "バナナ"], hint: "「ば」から はじまる 3もじの ことばだよ", displayAnswer: "バナナ", note: "黄色い皮をむいて食べます。", openEnded: false },
  { no: 3, genre: "食べもの", question: "外は緑のしましま、割ると中は赤。黒い種がならんでいるものは?", acceptableAnswers: ["すいか"], hint: "「す」から はじまる 3もじの ことばだよ", displayAnswer: "すいか", note: "夏に人気の大きな果物です。", openEnded: false },
  { no: 4, genre: "食べもの", question: "頭に葉っぱのかんむり。体はごつごつ、中は黄色くて甘ずっぱい果物は?", acceptableAnswers: ["ぱいなっぷる", "パイナップル"], hint: "「ぱ」から はじまる 5もじの ことばだよ", displayAnswer: "パイナップル", note: "葉の形がかんむりのように見えます。", openEnded: false },
  { no: 5, genre: "食べもの", question: "赤い体に、小さなつぶつぶを外側につけている果物は?", acceptableAnswers: ["いちご"], hint: "「い」から はじまる 3もじの ことばだよ", displayAnswer: "いちご", note: "種のようなつぶが表面に見えます。", openEnded: false },
  { no: 6, genre: "食べもの", question: "土の中で育つオレンジ色の野菜。うさぎが好きそうなものは?", acceptableAnswers: ["にんじん"], hint: "「に」から はじまる 4もじの ことばだよ", displayAnswer: "にんじん", note: "葉は地上に出て、食べる部分は土の中で育ちます。", openEnded: false },
  { no: 7, genre: "食べもの", question: "泣いていないのに、切ると涙が出てくる野菜は?", acceptableAnswers: ["たまねぎ"], hint: "「た」から はじまる 4もじの ことばだよ", displayAnswer: "たまねぎ", note: "切ると目を刺激する成分が広がります。", openEnded: false },
  { no: 8, genre: "食べもの", question: "ひげを生やして、黄色いつぶをきれいにならべている野菜は?", acceptableAnswers: ["とうもろこし"], hint: "「と」から はじまる 6もじの ことばだよ", displayAnswer: "とうもろこし", note: "皮をむくと黄色いつぶが列になっています。", openEnded: false },
  { no: 9, genre: "食べもの", question: "はじめは小さくてかたい粒。水といっしょにあたためると、白くふっくらするものは?", acceptableAnswers: ["おこめ", "お米", "ごはん"], hint: "「お」から はじまる 3もじの ことばだよ", displayAnswer: "お米(ごはん)", note: "お米を炊くと、ふっくらしたごはんになります。", openEnded: false },
  { no: 10, genre: "食べもの", question: "茶色や白のかたい殻を割ると、黄色と透明な部分に分かれているものは?", acceptableAnswers: ["たまご"], hint: "「た」から はじまる 3もじの ことばだよ", displayAnswer: "たまご", note: "黄身と白身が殻の中に入っています。", openEnded: false },
  { no: 11, genre: "食べもの", question: "白くて四角いことが多く、豆からできている食べものは?", acceptableAnswers: ["とうふ"], hint: "「と」から はじまる 3もじの ことばだよ", displayAnswer: "とうふ", note: "大豆から作られ、冷ややっこやみそ汁にも使われます。", openEnded: false },
  { no: 12, genre: "食べもの", question: "白いごはんの中で、赤くてすっぱい小さな主役になるものは?", acceptableAnswers: ["うめぼし"], hint: "「う」から はじまる 4もじの ことばだよ", displayAnswer: "うめぼし", note: "おにぎりの具にもなる、すっぱい食べものです。", openEnded: false },
  { no: 13, genre: "食べもの", question: "海で育つのに、紙のようにうすくなって、おにぎりに巻かれるものは?", acceptableAnswers: ["のり"], hint: "「の」から はじまる 2もじの ことばだよ", displayAnswer: "のり", note: "海藻から作られます。", openEnded: false },
  { no: 14, genre: "食べもの", question: "まんなかに穴があいている、甘い輪っかのおやつは?", acceptableAnswers: ["どーなつ", "ドーナツ"], hint: "「ど」から はじまる 4もじの ことばだよ", displayAnswer: "ドーナツ", note: "輪の形をしたものがよく知られています。", openEnded: false },
  { no: 15, genre: "食べもの", question: "冷たくて甘く、暑いところにいるとどんどん小さくなるおやつは?", acceptableAnswers: ["あいすくりーむ", "アイスクリーム"], hint: "「あ」から はじまる 7もじの ことばだよ", displayAnswer: "アイスクリーム", note: "あたたかいと溶けてしまいます。", openEnded: false },
  { no: 16, genre: "食べもの", question: "誕生日にろうそくを立てる、ふわふわで甘い食べものは?", acceptableAnswers: ["けーき", "ケーキ"], hint: "「け」から はじまる 3もじの ことばだよ", displayAnswer: "ケーキ", note: "誕生日のお祝いによく登場します。", openEnded: false },
  { no: 17, genre: "食べもの", question: "どんぶりの中のおふろに入り、長い体をつるつるっと食べられるものは?", acceptableAnswers: ["らーめん", "ラーメン"], hint: "「ら」から はじまる 4もじの ことばだよ", displayAnswer: "ラーメン", note: "めんがスープの中に入っています。", openEnded: false },
  { no: 18, genre: "食べもの", question: "小さくてかたい黄色の粒が、熱くなると白い花のようにはじけるおやつは?", acceptableAnswers: ["ぽっぷこーん", "ポップコーン"], hint: "「ぽ」から はじまる 5もじの ことばだよ", displayAnswer: "ポップコーン", note: "とうもろこしの粒が熱ではじけます。", openEnded: false },
  { no: 19, genre: "食べもの", question: "お祭りで見かける、雲のようにふわふわした甘いおやつは?", acceptableAnswers: ["わたあめ"], hint: "「わ」から はじまる 4もじの ことばだよ", displayAnswer: "わたあめ", note: "砂糖から作る、綿のようなお菓子です。", openEnded: false },
  { no: 20, genre: "食べもの", question: "小さな働き者が花から集める、金色でとても甘いものは?", acceptableAnswers: ["はちみつ"], hint: "「は」から はじまる 4もじの ことばだよ", displayAnswer: "はちみつ", note: "みつばちが花のみつを集めて作ります。", openEnded: false },
  { no: 21, genre: "どうぶつ", question: "大きな耳と長い鼻をもち、陸にすむ動物の中でとても大きいのは?", acceptableAnswers: ["ぞう"], hint: "「ぞ」から はじまる 2もじの ことばだよ", displayAnswer: "ぞう", note: "長い鼻を上手に使います。", openEnded: false },
  { no: 22, genre: "どうぶつ", question: "首がとても長く、高い木の葉を食べる動物は?", acceptableAnswers: ["きりん"], hint: "「き」から はじまる 3もじの ことばだよ", displayAnswer: "きりん", note: "長い首で高いところの葉にも届きます。", openEnded: false },
  { no: 23, genre: "どうぶつ", question: "白と黒の服を着て、竹をむしゃむしゃ食べる動物は?", acceptableAnswers: ["ぱんだ", "パンダ"], hint: "「ぱ」から はじまる 3もじの ことばだよ", displayAnswer: "パンダ", note: "白黒の体と竹が大きなヒントです。", openEnded: false },
  { no: 24, genre: "どうぶつ", question: "おなかに大きなポケットがあり、ぴょんぴょん進む動物は?", acceptableAnswers: ["かんがるー", "カンガルー"], hint: "「か」から はじまる 5もじの ことばだよ", displayAnswer: "カンガルー", note: "おなかの袋で子どもを育てます。", openEnded: false },
  { no: 25, genre: "どうぶつ", question: "白黒のしましまを着た、馬ににている動物は?", acceptableAnswers: ["しまうま"], hint: "「し」から はじまる 4もじの ことばだよ", displayAnswer: "しまうま", note: "一頭ずつしま模様が少しずつ違います。", openEnded: false },
  { no: 26, genre: "どうぶつ", question: "ふさふさのたてがみをもち、『百獣の王』とよばれる動物は?", acceptableAnswers: ["らいおん", "ライオン"], hint: "「ら」から はじまる 4もじの ことばだよ", displayAnswer: "ライオン", note: "オスの大きなたてがみが有名です。", openEnded: false },
  { no: 27, genre: "どうぶつ", question: "家を背中にのせたように見え、雨上がりにゆっくり歩く小さな生きものは?", acceptableAnswers: ["かたつむり"], hint: "「か」から はじまる 5もじの ことばだよ", displayAnswer: "かたつむり", note: "殻を背負ってゆっくり進みます。", openEnded: false },
  { no: 28, genre: "どうぶつ", question: "海にすみ、足が8本。びっくりすると墨を出す生きものは?", acceptableAnswers: ["たこ"], hint: "「た」から はじまる 2もじの ことばだよ", displayAnswer: "たこ", note: "8本の腕と墨がヒントです。", openEnded: false },
  { no: 29, genre: "どうぶつ", question: "横向きに歩き、両手がはさみの海の生きものは?", acceptableAnswers: ["かに"], hint: "「か」から はじまる 2もじの ことばだよ", displayAnswer: "かに", note: "左右に動く姿がよく知られています。", openEnded: false },
  { no: 30, genre: "どうぶつ", question: "池の近くでぴょんと跳び、『ケロケロ』と鳴く生きものは?", acceptableAnswers: ["かえる"], hint: "「か」から はじまる 3もじの ことばだよ", displayAnswer: "かえる", note: "おたまじゃくしから大きくなります。", openEnded: false },
  { no: 31, genre: "どうぶつ", question: "夜に飛び、どうくつなどで逆さまにぶら下がって休む動物は?", acceptableAnswers: ["こうもり"], hint: "「こ」から はじまる 4もじの ことばだよ", displayAnswer: "こうもり", note: "鳥ではなく、空を飛ぶほ乳類です。", openEnded: false },
  { no: 32, genre: "どうぶつ", question: "まわりに合わせて体の色を変えるのが上手な、トカゲの仲間は?", acceptableAnswers: ["かめれおん", "カメレオン"], hint: "「か」から はじまる 5もじの ことばだよ", displayAnswer: "カメレオン", note: "体色を変えたり、長い舌を使ったりします。", openEnded: false },
  { no: 33, genre: "どうぶつ", question: "大きく広げると、しっぽが美しい扇のようになる鳥は?", acceptableAnswers: ["くじゃく"], hint: "「く」から はじまる 3もじの ことばだよ", displayAnswer: "くじゃく", note: "オスの美しい飾り羽が有名です。", openEnded: false },
  { no: 34, genre: "どうぶつ", question: "白黒の礼服を着ているように見え、飛べないけれど泳ぎが上手な鳥は?", acceptableAnswers: ["ぺんぎん", "ペンギン"], hint: "「ぺ」から はじまる 4もじの ことばだよ", displayAnswer: "ペンギン", note: "翼を使って水の中をすばやく泳ぎます。", openEnded: false },
  { no: 35, genre: "どうぶつ", question: "冬になると長く眠ることがあり、はちみつが好きなイメージの動物は?", acceptableAnswers: ["くま"], hint: "「く」から はじまる 2もじの ことばだよ", displayAnswer: "くま", note: "種類によっては冬ごもりをします。", openEnded: false },
  { no: 36, genre: "どうぶつ", question: "長い耳でぴょんぴょん跳び、にんじんが似合う動物は?", acceptableAnswers: ["うさぎ"], hint: "「う」から はじまる 3もじの ことばだよ", displayAnswer: "うさぎ", note: "長い耳と強い後ろ足をもっています。", openEnded: false },
  { no: 37, genre: "どうぶつ", question: "人の言葉をまねるのが上手で、色あざやかな羽をもつ鳥は?", acceptableAnswers: ["おうむ", "オウム"], hint: "「お」から はじまる 3もじの ことばだよ", displayAnswer: "オウム", note: "聞いた音をまねることがあります。", openEnded: false },
  { no: 38, genre: "どうぶつ", question: "立ったまま眠ることがあり、背中に人を乗せて走る動物は?", acceptableAnswers: ["うま"], hint: "「う」から はじまる 2もじの ことばだよ", displayAnswer: "うま", note: "昔から人や荷物を運んできました。", openEnded: false },
  { no: 39, genre: "どうぶつ", question: "ひげをもち、のどをゴロゴロ鳴らすことがある身近な動物は?", acceptableAnswers: ["ねこ"], hint: "「ね」から はじまる 2もじの ことばだよ", displayAnswer: "ねこ", note: "うれしいときなどにゴロゴロ音を出します。", openEnded: false },
  { no: 40, genre: "どうぶつ", question: "うれしいとしっぽをふり、『ワンワン』と鳴く身近な動物は?", acceptableAnswers: ["いぬ"], hint: "「い」から はじまる 2もじの ことばだよ", displayAnswer: "いぬ", note: "人と昔から暮らしてきた動物です。", openEnded: false },
  { no: 41, genre: "自然・季節", question: "朝は東から顔を出し、夕方は西へ帰っていく、空の大きな光は?", acceptableAnswers: ["たいよう", "太陽"], hint: "「た」から はじまる 4もじの ことばだよ", displayAnswer: "太陽", note: "地球から見ると、東から西へ動くように見えます。", openEnded: false },
  { no: 42, genre: "自然・季節", question: "夜空に見え、日によって丸くなったり細くなったりするものは?", acceptableAnswers: ["つき", "月"], hint: "「つ」から はじまる 2もじの ことばだよ", displayAnswer: "月", note: "月の満ち欠けで形が変わって見えます。", openEnded: false },
  { no: 43, genre: "自然・季節", question: "夜空にちらばる、とても遠くの小さな光は?", acceptableAnswers: ["ほし", "星"], hint: "「ほ」から はじまる 2もじの ことばだよ", displayAnswer: "星", note: "本当は大きくても、遠いので小さく見えます。", openEnded: false },
  { no: 44, genre: "自然・季節", question: "足がないのに空を流れ、ときどき雨を運んでくるものは?", acceptableAnswers: ["くも", "雲"], hint: "「く」から はじまる 2もじの ことばだよ", displayAnswer: "雲", note: "風に流され、雨や雪を降らせます。", openEnded: false },
  { no: 45, genre: "自然・季節", question: "目には見えないのに、木の葉や旗をゆらすものは?", acceptableAnswers: ["かぜ", "風"], hint: "「か」から はじまる 2もじの ことばだよ", displayAnswer: "風", note: "空気が動くことで風になります。", openEnded: false },
  { no: 46, genre: "自然・季節", question: "雨上がりの空にかかる、七色の大きな橋は?", acceptableAnswers: ["にじ", "虹"], hint: "「に」から はじまる 2もじの ことばだよ", displayAnswer: "虹", note: "太陽の光が雨つぶで分かれて見えます。", openEnded: false },
  { no: 47, genre: "自然・季節", question: "空にある見えないじょうろから、たくさんの水のつぶが落ちてくるものは?", acceptableAnswers: ["あめ", "雨"], hint: "「あ」から はじまる 2もじの ことばだよ", displayAnswer: "雨", note: "雲の中の水滴が大きくなって落ちます。", openEnded: false },
  { no: 48, genre: "自然・季節", question: "冬の空から落ちてくる、白くて冷たい花のようなものは?", acceptableAnswers: ["ゆき", "雪"], hint: "「ゆ」から はじまる 2もじの ことばだよ", displayAnswer: "雪", note: "氷の結晶が集まってできています。", openEnded: false },
  { no: 49, genre: "自然・季節", question: "春に咲き、町や公園をピンク色にする花は?", acceptableAnswers: ["さくら"], hint: "「さ」から はじまる 3もじの ことばだよ", displayAnswer: "さくら", note: "日本の春を代表する花です。", openEnded: false },
  { no: 50, genre: "自然・季節", question: "夏の木で大きな声で歌い、地面にはぬけがらを残す虫は?", acceptableAnswers: ["せみ"], hint: "「せ」から はじまる 2もじの ことばだよ", displayAnswer: "せみ", note: "幼虫は土の中で育ちます。", openEnded: false },
  { no: 51, genre: "自然・季節", question: "秋になると緑から赤や黄色へ服を着がえる木の葉は?", acceptableAnswers: ["こうよう", "もみじ", "紅葉"], hint: "「も」から はじまる 3もじの ことばだよ", displayAnswer: "紅葉(こうよう)", note: "気温などの変化で葉の色が変わります。", openEnded: false },
  { no: 52, genre: "自然・季節", question: "山で『ヤッホー』と呼ぶと、同じ声を返してくれるものは?", acceptableAnswers: ["やまびこ"], hint: "「や」から はじまる 4もじの ことばだよ", displayAnswer: "やまびこ", note: "声が山などに反射して戻ってきます。", openEnded: false },
  { no: 53, genre: "自然・季節", question: "寒い日に屋根の下から下向きに伸びる、透明な氷の棒は?", acceptableAnswers: ["つらら"], hint: "「つ」から はじまる 3もじの ことばだよ", displayAnswer: "つらら", note: "溶けた雪の水が凍りながら伸びます。", openEnded: false },
  { no: 54, genre: "自然・季節", question: "とても広くてしょっぱく、魚やくじらが暮らす場所は?", acceptableAnswers: ["うみ", "海"], hint: "「う」から はじまる 2もじの ことばだよ", displayAnswer: "海", note: "地球の表面の多くをおおっています。", openEnded: false },
  { no: 55, genre: "自然・季節", question: "足はないのに山から町へ流れ、最後は海へ向かうものは?", acceptableAnswers: ["かわ", "川"], hint: "「か」から はじまる 2もじの ことばだよ", displayAnswer: "川", note: "高い場所から低い場所へ水が流れます。", openEnded: false },
  { no: 56, genre: "自然・季節", question: "大きな岩や土でできていて、いちばん高いところを『頂上』というものは?", acceptableAnswers: ["やま", "山"], hint: "「や」から はじまる 2もじの ことばだよ", displayAnswer: "山", note: "頂上へ向かって登ることを登山といいます。", openEnded: false },
  { no: 57, genre: "自然・季節", question: "土の中にかくれて水を飲み、木や草をしっかり支えているものは?", acceptableAnswers: ["ね", "根"], hint: "「ね」から はじまる 1もじの ことばだよ", displayAnswer: "根", note: "植物は根から水や養分を取りこみます。", openEnded: false },
  { no: 58, genre: "自然・季節", question: "黄色い大きな顔をもち、太陽のほうを向く名前の花は?", acceptableAnswers: ["ひまわり"], hint: "「ひ」から はじまる 4もじの ことばだよ", displayAnswer: "ひまわり", note: "『日(太陽)を回る』ような名前の花です。", openEnded: false },
  { no: 59, genre: "自然・季節", question: "見えないし、においもほとんどない。でも、ないと息ができないものは?", acceptableAnswers: ["くうき", "空気"], hint: "「く」から はじまる 3もじの ことばだよ", displayAnswer: "空気", note: "人や動物が呼吸するために必要です。", openEnded: false },
  { no: 60, genre: "自然・季節", question: "朝、草の先に小さなガラス玉のようについている水のつぶは?", acceptableAnswers: ["あさつゆ", "朝露"], hint: "「あ」から はじまる 4もじの ことばだよ", displayAnswer: "朝露(あさつゆ)", note: "空気中の水分が冷えて水滴になります。", openEnded: false },
  { no: 61, genre: "家の中・身の回り", question: "歯がたくさんあるのに、食べものをかめないものは?", acceptableAnswers: ["くし"], hint: "「く」から はじまる 2もじの ことばだよ", displayAnswer: "くし", note: "たくさん並んだ部分を『歯』といいます。", openEnded: false },
  { no: 62, genre: "家の中・身の回り", question: "足が1本、頭は大きい。雨の日に人の上で開くものは?", acceptableAnswers: ["かさ"], hint: "「か」から はじまる 2もじの ことばだよ", displayAnswer: "かさ", note: "開くと雨から守ってくれます。", openEnded: false },
  { no: 63, genre: "家の中・身の回り", question: "足が4本あることが多いのに歩けず、上でごはんを食べる家具は?", acceptableAnswers: ["てーぶる", "テーブル"], hint: "「て」から はじまる 4もじの ことばだよ", displayAnswer: "テーブル", note: "脚はあっても自分では歩きません。", openEnded: false },
  { no: 64, genre: "家の中・身の回り", question: "手はあるのに腕がなく、休まず時間を教えるものは?", acceptableAnswers: ["とけい", "時計"], hint: "「と」から はじまる 3もじの ことばだよ", displayAnswer: "時計", note: "長い針と短い針を『手』にたとえています。", openEnded: false },
  { no: 65, genre: "家の中・身の回り", question: "大きな白い箱。食べものを入れると、冷たくして長もちさせるものは?", acceptableAnswers: ["れいぞうこ", "冷蔵庫"], hint: "「れ」から はじまる 5もじの ことばだよ", displayAnswer: "冷蔵庫", note: "中を低い温度に保ちます。", openEnded: false },
  { no: 66, genre: "家の中・身の回り", question: "水を飲みこみ、服をぐるぐる回してきれいにする機械は?", acceptableAnswers: ["せんたくき", "洗濯機"], hint: "「せ」から はじまる 5もじの ことばだよ", displayAnswer: "洗濯機", note: "水と洗剤で衣類を洗います。", openEnded: false },
  { no: 67, genre: "家の中・身の回り", question: "ふだんは黒い顔。スイッチを入れると、ニュースやアニメを見せるものは?", acceptableAnswers: ["てれび", "テレビ"], hint: "「て」から はじまる 3もじの ことばだよ", displayAnswer: "テレビ", note: "画面に映像を映します。", openEnded: false },
  { no: 68, genre: "家の中・身の回り", question: "夜になると広げて、人が中にもぐって眠るものは?", acceptableAnswers: ["ふとん"], hint: "「ふ」から はじまる 3もじの ことばだよ", displayAnswer: "ふとん", note: "体をあたたかくして眠れます。", openEnded: false },
  { no: 69, genre: "家の中・身の回り", question: "家の口のような場所で、人が出入りするたびに開いたり閉じたりするものは?", acceptableAnswers: ["どあ", "ドア"], hint: "「ど」から はじまる 2もじの ことばだよ", displayAnswer: "ドア", note: "部屋や家の出入り口にあります。", openEnded: false },
  { no: 70, genre: "家の中・身の回り", question: "こちらが笑うと向こうも笑う。でも一言も話さないものは?", acceptableAnswers: ["かがみ", "鏡"], hint: "「か」から はじまる 3もじの ことばだよ", displayAnswer: "鏡", note: "目の前の姿をそのまま映します。", openEnded: false },
  { no: 71, genre: "家の中・身の回り", question: "字を消すたびに、少しずつ体が小さくなる文房具は?", acceptableAnswers: ["けしごむ", "消しごむ", "消しゴム"], hint: "「け」から はじまる 4もじの ことばだよ", displayAnswer: "消しゴム", note: "こすると削れて小さくなります。", openEnded: false },
  { no: 72, genre: "家の中・身の回り", question: "字を書けば書くほど、だんだん背が低くなる文房具は?", acceptableAnswers: ["えんぴつ"], hint: "「え」から はじまる 4もじの ことばだよ", displayAnswer: "えんぴつ", note: "削りながら使うので短くなります。", openEnded: false },
  { no: 73, genre: "家の中・身の回り", question: "小さな歯が一列にならび、服やかばんの口を開け閉めするものは?", acceptableAnswers: ["ふぁすなー", "ファスナー"], hint: "「ふ」から はじまる 4もじの ことばだよ", displayAnswer: "ファスナー", note: "引き手を動かすと歯がかみ合います。", openEnded: false },
  { no: 74, genre: "家の中・身の回り", question: "2本の刃が、口をぱくぱくさせるように紙を切る道具は?", acceptableAnswers: ["はさみ"], hint: "「は」から はじまる 3もじの ことばだよ", displayAnswer: "はさみ", note: "2枚の刃を動かして切ります。", openEnded: false },
  { no: 75, genre: "家の中・身の回り", question: "おなかがいっぱいになるほどうれしいけれど、中身はごみばかりのものは?", acceptableAnswers: ["ごみばこ", "ごみ箱"], hint: "「ご」から はじまる 4もじの ことばだよ", displayAnswer: "ごみ箱", note: "ごみを集めるための箱です。", openEnded: false },
  { no: 76, genre: "家の中・身の回り", question: "床のほこりをどんどん吸いこみ、部屋をきれいにする機械は?", acceptableAnswers: ["そうじき", "掃除機"], hint: "「そ」から はじまる 4もじの ことばだよ", displayAnswer: "掃除機", note: "空気といっしょにほこりを吸います。", openEnded: false },
  { no: 77, genre: "家の中・身の回り", question: "目は1つ。暗いところで、その目から明るい光を出す道具は?", acceptableAnswers: ["かいちゅうでんとう", "懐中電灯"], hint: "「か」から はじまる 8もじの ことばだよ", displayAnswer: "懐中電灯", note: "持ち運べる小さな照明です。", openEnded: false },
  { no: 78, genre: "家の中・身の回り", question: "家の入り口で『ピンポーン』と鳴き、お客さんが来たことを知らせるものは?", acceptableAnswers: ["いんたーほん", "よびりん", "インターホン", "呼び鈴"], hint: "「よ」から はじまる 4もじの ことばだよ", displayAnswer: "インターホン(呼び鈴)", note: "ボタンを押すと家の中で音が鳴ります。", openEnded: false },
  { no: 79, genre: "家の中・身の回り", question: "自分は動かないのに、人を上へも下へも行かせる段々は?", acceptableAnswers: ["かいだん", "階段"], hint: "「か」から はじまる 4もじの ことばだよ", displayAnswer: "階段", note: "人が段を一つずつ上り下りします。", openEnded: false },
  { no: 80, genre: "家の中・身の回り", question: "小さいのに、ぴったり合うと大きなドアまで開けられるものは?", acceptableAnswers: ["かぎ"], hint: "「か」から はじまる 2もじの ことばだよ", displayAnswer: "かぎ", note: "形の合う鍵穴に入れて使います。", openEnded: false },
  { no: 81, genre: "学校・文房具", question: "先生が前に立って字や絵を書き、授業が終わるときれいに消される大きな板は?", acceptableAnswers: ["こくばん", "黒板"], hint: "「こ」から はじまる 4もじの ことばだよ", displayAnswer: "黒板", note: "チョークで書く大きな板です。", openEnded: false },
  { no: 82, genre: "学校・文房具", question: "黒い板に白い道を作り、書くほど短くなるものは?", acceptableAnswers: ["ちょーく", "チョーク"], hint: "「ち」から はじまる 3もじの ことばだよ", displayAnswer: "チョーク", note: "黒板に字を書くと少しずつ減ります。", openEnded: false },
  { no: 83, genre: "学校・文房具", question: "教科書やノートを背負って学校へ行く、子どもの相棒は?", acceptableAnswers: ["らんどせる", "ランドセル"], hint: "「ら」から はじまる 5もじの ことばだよ", displayAnswer: "ランドセル", note: "学用品を入れて背中に背負います。", openEnded: false },
  { no: 84, genre: "学校・文房具", question: "授業ごとにちがう知識がつまった、学校で使う本は?", acceptableAnswers: ["きょうかしょ", "教科書"], hint: "「き」から はじまる 4もじの ことばだよ", displayAnswer: "教科書", note: "教科ごとに学ぶ内容がまとめられています。", openEnded: false },
  { no: 85, genre: "学校・文房具", question: "まっすぐな線を引いたり、長さをはかったりする細長い道具は?", acceptableAnswers: ["じょうぎ", "定規"], hint: "「じ」から はじまる 3もじの ことばだよ", displayAnswer: "定規", note: "目盛りを使って長さを測れます。", openEnded: false },
  { no: 86, genre: "学校・文房具", question: "インクを少しずつ出しながら、紙の上を走って字を書くものは?", acceptableAnswers: ["ぺん", "ペン"], hint: "「ぺ」から はじまる 2もじの ことばだよ", displayAnswer: "ペン", note: "先からインクを出して書きます。", openEnded: false },
  { no: 87, genre: "学校・文房具", question: "えんぴつたちが、チャックの口を閉じて中で休む入れものは?", acceptableAnswers: ["ふでばこ", "筆箱"], hint: "「ふ」から はじまる 4もじの ことばだよ", displayAnswer: "筆箱", note: "文房具をまとめて入れます。", openEnded: false },
  { no: 88, genre: "学校・文房具", question: "知らない言葉をたずねると、意味を教えてくれる分厚い本は?", acceptableAnswers: ["じしょ", "辞書"], hint: "「じ」から はじまる 2もじの ことばだよ", displayAnswer: "辞書", note: "言葉の意味や使い方がのっています。", openEnded: false },
  { no: 89, genre: "学校・文房具", question: "四角い部屋がたくさんあり、日付や曜日を教えてくれるものは?", acceptableAnswers: ["かれんだー", "カレンダー"], hint: "「か」から はじまる 5もじの ことばだよ", displayAnswer: "カレンダー", note: "月ごとに日付が並んでいます。", openEnded: false },
  { no: 90, genre: "学校・文房具", question: "電話ではないのに、授業の始まりと終わりに鳴るものは?", acceptableAnswers: ["ちゃいむ", "チャイム"], hint: "「ち」から はじまる 3もじの ことばだよ", displayAnswer: "チャイム", note: "時間の区切りを音で知らせます。", openEnded: false },
  { no: 91, genre: "学校・文房具", question: "走る人から走る人へわたされる、リレーの大切な棒は?", acceptableAnswers: ["ばとん", "バトン"], hint: "「ば」から はじまる 3もじの ことばだよ", displayAnswer: "バトン", note: "次の走者へ手わたします。", openEnded: false },
  { no: 92, genre: "学校・文房具", question: "丸い体で、けられたり投げられたり、はずんだりする運動の道具は?", acceptableAnswers: ["ぼーる", "ボール"], hint: "「ぼ」から はじまる 3もじの ことばだよ", displayAnswer: "ボール", note: "いろいろなスポーツで使われます。", openEnded: false },
  { no: 93, genre: "学校・文房具", question: "白と黒の歯がならんでいるけれど、かむのではなく音楽をかなでるものは?", acceptableAnswers: ["ぴあの", "ピアノ"], hint: "「ぴ」から はじまる 3もじの ことばだよ", displayAnswer: "ピアノ", note: "白鍵と黒鍵を押して演奏します。", openEnded: false },
  { no: 94, genre: "学校・文房具", question: "細長い体に穴がいくつもあり、息を入れると歌う楽器は?", acceptableAnswers: ["りこーだー", "リコーダー"], hint: "「り」から はじまる 5もじの ことばだよ", displayAnswer: "リコーダー", note: "穴を指で押さえながら吹きます。", openEnded: false },
  { no: 95, genre: "学校・文房具", question: "4本足でも歩かず、教室でみんなを座らせてくれるものは?", acceptableAnswers: ["いす"], hint: "「い」から はじまる 2もじの ことばだよ", displayAnswer: "いす", note: "人が腰かける家具です。", openEnded: false },
  { no: 96, genre: "学校・文房具", question: "先生が丸や直しを書くときに使う、目立つ色の筆記具は?", acceptableAnswers: ["あかぺん", "赤ぺん", "赤ペン"], hint: "「あ」から はじまる 4もじの ことばだよ", displayAnswer: "赤ペン", note: "赤い字は答え合わせで見つけやすい色です。", openEnded: false },
  { no: 97, genre: "学校・文房具", question: "えんぴつを口から入れると、先をとがらせて出してくれる道具は?", acceptableAnswers: ["えんぴつけずり", "えんぴつ削り"], hint: "「え」から はじまる 7もじの ことばだよ", displayAnswer: "えんぴつ削り", note: "刃で木と芯を削ります。", openEnded: false },
  { no: 98, genre: "学校・文房具", question: "片面がぺたぺたして、切れた紙や工作の材料をくっつけるものは?", acceptableAnswers: ["せろはんてーぷ", "セロハンテープ"], hint: "「せ」から はじまる 7もじの ことばだよ", displayAnswer: "セロハンテープ", note: "粘着面で物を貼り合わせます。", openEnded: false },
  { no: 99, genre: "学校・文房具", question: "口はないのに、開くと物語や知識をたくさん話してくれるものは?", acceptableAnswers: ["ほん", "本"], hint: "「ほ」から はじまる 2もじの ことばだよ", displayAnswer: "本", note: "ページを読むと内容が伝わります。", openEnded: false },
  { no: 100, genre: "学校・文房具", question: "白い帯を引くと、書きまちがいを上からかくしてくれる文房具は?", acceptableAnswers: ["しゅうせいてーぷ", "修正てーぷ", "修正テープ"], hint: "「し」から はじまる 7もじの ことばだよ", displayAnswer: "修正テープ", note: "白いテープで文字をおおいます。", openEnded: false },
  { no: 101, genre: "町・乗りもの", question: "4つのタイヤで道路を走り、人や荷物を運ぶ乗りものは?", acceptableAnswers: ["じどうしゃ", "自動車"], hint: "「じ」から はじまる 4もじの ことばだよ", displayAnswer: "自動車", note: "エンジンなどの力で道路を走ります。", openEnded: false },
  { no: 102, genre: "町・乗りもの", question: "長い部屋がいくつもつながり、線路の上を走る乗りものは?", acceptableAnswers: ["でんしゃ", "電車"], hint: "「で」から はじまる 3もじの ことばだよ", displayAnswer: "電車", note: "車両が連なって線路を走ります。", openEnded: false },
  { no: 103, genre: "町・乗りもの", question: "タイヤが2つ。足でペダルをこいで進む乗りものは?", acceptableAnswers: ["じてんしゃ", "自転車"], hint: "「じ」から はじまる 4もじの ことばだよ", displayAnswer: "自転車", note: "人の力でペダルを回して進みます。", openEnded: false },
  { no: 104, genre: "町・乗りもの", question: "大きな翼をもち、人を乗せて雲より高く飛ぶ乗りものは?", acceptableAnswers: ["ひこうき", "飛行機"], hint: "「ひ」から はじまる 4もじの ことばだよ", displayAnswer: "飛行機", note: "翼に生まれる力で空を飛びます。", openEnded: false },
  { no: 105, genre: "町・乗りもの", question: "水の上に浮かび、海や川を進む大きな乗りものは?", acceptableAnswers: ["ふね", "船"], hint: "「ふ」から はじまる 2もじの ことばだよ", displayAnswer: "船", note: "人や荷物を水の上で運びます。", openEnded: false },
  { no: 106, genre: "町・乗りもの", question: "赤い体でサイレンを鳴らし、火事の場所へ急ぐ車は?", acceptableAnswers: ["しょうぼうしゃ", "消防車"], hint: "「し」から はじまる 5もじの ことばだよ", displayAnswer: "消防車", note: "消火のための水や道具を運びます。", openEnded: false },
  { no: 107, genre: "町・乗りもの", question: "具合の悪い人やけが人を病院へ急いで運ぶ、白い車は?", acceptableAnswers: ["きゅうきゅうしゃ", "救急車"], hint: "「き」から はじまる 5もじの ことばだよ", displayAnswer: "救急車", note: "救急隊員と医療の道具を乗せています。", openEnded: false },
  { no: 108, genre: "町・乗りもの", question: "町の安全を守る人が乗り、赤いランプをつけて走る車は?", acceptableAnswers: ["ぱとかー", "パトカー"], hint: "「ぱ」から はじまる 4もじの ことばだよ", displayAnswer: "パトカー", note: "警察官が町の見回りなどに使います。", openEnded: false },
  { no: 109, genre: "町・乗りもの", question: "ビルの中を、箱ごと上や下へ運んでくれるものは?", acceptableAnswers: ["えれべーたー", "エレベーター"], hint: "「え」から はじまる 6もじの ことばだよ", displayAnswer: "エレベーター", note: "箱のようなかごが上下に動きます。", openEnded: false },
  { no: 110, genre: "町・乗りもの", question: "階段なのに自分で動き、人を上や下へ運ぶものは?", acceptableAnswers: ["えすかれーたー", "エスカレーター"], hint: "「え」から はじまる 7もじの ことばだよ", displayAnswer: "エスカレーター", note: "階段状のステップが連続して動きます。", openEnded: false },
  { no: 111, genre: "町・乗りもの", question: "赤は止まれ、青は進め。道路で色を変えて指示するものは?", acceptableAnswers: ["しんごうき", "信号機"], hint: "「し」から はじまる 5もじの ことばだよ", displayAnswer: "信号機", note: "車や歩行者の動きを色で分けます。", openEnded: false },
  { no: 112, genre: "町・乗りもの", question: "道路のそばで、丸や三角の顔を使ってルールを教えるものは?", acceptableAnswers: ["どうろひょうしき", "道路標識"], hint: "「ど」から はじまる 7もじの ことばだよ", displayAnswer: "道路標識", note: "形や絵、文字で交通ルールを示します。", openEnded: false },
  { no: 113, genre: "町・乗りもの", question: "足はないのに、切手をつけると遠くの人へ旅をする紙は?", acceptableAnswers: ["てがみ", "手紙"], hint: "「て」から はじまる 3もじの ことばだよ", displayAnswer: "手紙", note: "郵便で相手のもとへ届きます。", openEnded: false },
  { no: 114, genre: "町・乗りもの", question: "お金を入れてボタンを押すと、飲みものなどを出してくれる箱は?", acceptableAnswers: ["じどうはんばいき", "自動販売機"], hint: "「じ」から はじまる 8もじの ことばだよ", displayAnswer: "自動販売機", note: "店員さんがいなくても商品を買えます。", openEnded: false },
  { no: 115, genre: "町・乗りもの", question: "お金やカードを入れると、電車に乗るための紙を出す機械は?", acceptableAnswers: ["けんばいき", "券売機"], hint: "「け」から はじまる 5もじの ことばだよ", displayAnswer: "券売機", note: "きっぷを買うための機械です。", openEnded: false },
  { no: 116, genre: "町・乗りもの", question: "雨ではないのに、公園で水を空へ高くふき上げるものは?", acceptableAnswers: ["ふんすい", "噴水"], hint: "「ふ」から はじまる 4もじの ことばだよ", displayAnswer: "噴水", note: "水を循環させてふき上げます。", openEnded: false },
  { no: 117, genre: "町・乗りもの", question: "走りつかれた車たちが、きれいに並んで休む場所は?", acceptableAnswers: ["ちゅうしゃじょう", "駐車場"], hint: "「ち」から はじまる 5もじの ことばだよ", displayAnswer: "駐車場", note: "車をとめておく場所です。", openEnded: false },
  { no: 118, genre: "町・乗りもの", question: "たくさんの本が静かに集まり、借りることもできる場所は?", acceptableAnswers: ["としょかん", "図書館"], hint: "「と」から はじまる 4もじの ことばだよ", displayAnswer: "図書館", note: "本や資料を読んだり借りたりできます。", openEnded: false },
  { no: 119, genre: "町・乗りもの", question: "大きな建物の中に、いろいろなお店が集まっている場所は?", acceptableAnswers: ["しょっぴんぐもーる", "ショッピングモール"], hint: "「し」から はじまる 7もじの ことばだよ", displayAnswer: "ショッピングモール", note: "買いものや食事ができる店が集まっています。", openEnded: false },
  { no: 120, genre: "町・乗りもの", question: "道路に太い白いしまがならび、人が安全に渡る場所は?", acceptableAnswers: ["おうだんほどう", "横断歩道"], hint: "「お」から はじまる 7もじの ことばだよ", displayAnswer: "横断歩道", note: "歩行者が道路を横切るための場所です。", openEnded: false },
  { no: 121, genre: "からだ", question: "顔にある2つの窓。開けると世界が見えるものは?", acceptableAnswers: ["め", "目"], hint: "「め」から はじまる 1もじの ことばだよ", displayAnswer: "目", note: "光を受け取って物を見ます。", openEnded: false },
  { no: 122, genre: "からだ", question: "顔のまんなかにある橋のような形で、においを見つけるものは?", acceptableAnswers: ["はな", "鼻"], hint: "「は」から はじまる 2もじの ことばだよ", displayAnswer: "鼻", note: "においを感じ、呼吸にも使います。", openEnded: false },
  { no: 123, genre: "からだ", question: "骨がないのに、味を調べたり言葉を作るのを手伝ったりするものは?", acceptableAnswers: ["した", "舌"], hint: "「し」から はじまる 2もじの ことばだよ", displayAnswer: "舌", note: "味を感じ、話すときにも動きます。", openEnded: false },
  { no: 124, genre: "からだ", question: "口の中にならぶ白くてかたい仲間。食べものを小さくするものは?", acceptableAnswers: ["は", "歯"], hint: "「は」から はじまる 1もじの ことばだよ", displayAnswer: "歯", note: "かんだりすりつぶしたりします。", openEnded: false },
  { no: 125, genre: "からだ", question: "顔の左右にあり、音を集める2つのものは?", acceptableAnswers: ["みみ", "耳"], hint: "「み」から はじまる 2もじの ことばだよ", displayAnswer: "耳", note: "空気の振動を音として感じます。", openEnded: false },
  { no: 126, genre: "からだ", question: "切っても痛くなく、しばらくするとまた長くなる、頭にあるものは?", acceptableAnswers: ["かみのけ", "髪の毛"], hint: "「か」から はじまる 4もじの ことばだよ", displayAnswer: "髪の毛", note: "皮ふから出ている部分には痛みを感じません。", openEnded: false },
  { no: 127, genre: "からだ", question: "手の先にならぶ5人きょうだい。物をつかむときに働くものは?", acceptableAnswers: ["ゆび", "指"], hint: "「ゆ」から はじまる 2もじの ことばだよ", displayAnswer: "指", note: "親指から小指まで協力して動きます。", openEnded: false },
  { no: 128, genre: "からだ", question: "明るいところではいつもついてくるのに、暗くなるとかくれるものは?", acceptableAnswers: ["かげ", "影"], hint: "「か」から はじまる 2もじの ことばだよ", displayAnswer: "影", note: "光が体にさえぎられてできます。", openEnded: false },
  { no: 129, genre: "からだ", question: "胸の中で、休まず『ドクンドクン』と動くものは?", acceptableAnswers: ["しんぞう", "心臓"], hint: "「し」から はじまる 4もじの ことばだよ", displayAnswer: "心臓", note: "全身へ血液を送るポンプの役目をします。", openEnded: false },
  { no: 130, genre: "からだ", question: "眠っていても続き、吸ったりはいたりしているものは?", acceptableAnswers: ["こきゅう", "呼吸"], hint: "「こ」から はじまる 3もじの ことばだよ", displayAnswer: "呼吸", note: "体に酸素を取りこむために続いています。", openEnded: false },
  { no: 131, genre: "からだ", question: "目の前にある2つのカーテン。閉じると目を守るものは?", acceptableAnswers: ["まぶた"], hint: "「ま」から はじまる 3もじの ことばだよ", displayAnswer: "まぶた", note: "まばたきで目の表面を守ります。", openEnded: false },
  { no: 132, genre: "からだ", question: "食べたり話したり笑ったりするときに開く、顔にあるものは?", acceptableAnswers: ["くち", "口"], hint: "「く」から はじまる 2もじの ことばだよ", displayAnswer: "口", note: "食事や会話などで使います。", openEnded: false },
  { no: 133, genre: "からだ", question: "指先についた小さなかたい盾。伸びると切って整えるものは?", acceptableAnswers: ["つめ"], hint: "「つ」から はじまる 2もじの ことばだよ", displayAnswer: "つめ", note: "指先を守り、細かな作業も助けます。", openEnded: false },
  { no: 134, genre: "からだ", question: "腕のまんなかで曲がり、ぶつけるとジーンとすることがある場所は?", acceptableAnswers: ["ひじ"], hint: "「ひ」から はじまる 2もじの ことばだよ", displayAnswer: "ひじ", note: "腕を曲げ伸ばしする関節です。", openEnded: false },
  { no: 135, genre: "からだ", question: "足のまんなかで曲がり、歩いたりしゃがんだりするときに使う場所は?", acceptableAnswers: ["ひざ"], hint: "「ひ」から はじまる 2もじの ことばだよ", displayAnswer: "ひざ", note: "足を曲げ伸ばしする関節です。", openEnded: false },
  { no: 136, genre: "からだ", question: "足のいちばん下で地面にふれ、体を支えている場所は?", acceptableAnswers: ["あしのうら", "足の裏"], hint: "「あ」から はじまる 5もじの ことばだよ", displayAnswer: "足の裏", note: "立ったり歩いたりするとき体重を支えます。", openEnded: false },
  { no: 137, genre: "からだ", question: "寒いときやびっくりしたとき、皮ふに小さく並ぶぶつぶつは?", acceptableAnswers: ["とりはだ", "鳥肌"], hint: "「と」から はじまる 4もじの ことばだよ", displayAnswer: "鳥肌", note: "毛の根元の筋肉が縮んでできます。", openEnded: false },
  { no: 138, genre: "からだ", question: "眠くなると口が大きく開いて、思わず出てしまうものは?", acceptableAnswers: ["あくび"], hint: "「あ」から はじまる 3もじの ことばだよ", displayAnswer: "あくび", note: "眠いときや退屈なときなどに出ます。", openEnded: false },
  { no: 139, genre: "からだ", question: "走ったり暑くなったりすると、体から出てくるしょっぱい水は?", acceptableAnswers: ["あせ", "汗"], hint: "「あ」から はじまる 2もじの ことばだよ", displayAnswer: "汗", note: "体の熱を逃がすのを助けます。", openEnded: false },
  { no: 140, genre: "からだ", question: "目には見えないけれど、口から出て、耳で聞くことができるものは?", acceptableAnswers: ["こえ", "声"], hint: "「こ」から はじまる 2もじの ことばだよ", displayAnswer: "声", note: "のどで作られた音が空気を伝わります。", openEnded: false },
  { no: 141, genre: "ことば遊び", question: "『ぼうし』の中にかくれている動物は?", acceptableAnswers: ["うし"], hint: "「う」から はじまる 2もじの ことばだよ", displayAnswer: "うし", note: "『ぼ・うし』の中に『うし』があります。", openEnded: false },
  { no: 142, genre: "ことば遊び", question: "『れいぞうこ』の中にかくれている大きな動物は?", acceptableAnswers: ["ぞう"], hint: "「ぞ」から はじまる 2もじの ことばだよ", displayAnswer: "ぞう", note: "『れい・ぞう・こ』の中に『ぞう』があります。", openEnded: false },
  { no: 143, genre: "ことば遊び", question: "『しかく』の中にかくれている動物は?", acceptableAnswers: ["しか"], hint: "「し」から はじまる 2もじの ことばだよ", displayAnswer: "しか", note: "『しか・く』のはじめに『しか』があります。", openEnded: false },
  { no: 144, genre: "ことば遊び", question: "『サイコロ』の中にかくれている動物は?", acceptableAnswers: ["さい", "サイ"], hint: "「さ」から はじまる 2もじの ことばだよ", displayAnswer: "サイ", note: "『サイ・コロ』のはじめに『サイ』があります。", openEnded: false },
  { no: 145, genre: "ことば遊び", question: "『トナカイ』の中にかくれている海のものは?", acceptableAnswers: ["かい", "貝"], hint: "「か」から はじまる 2もじの ことばだよ", displayAnswer: "貝(かい)", note: "『トナ・カイ』の終わりに『かい』があります。", openEnded: false },
  { no: 146, genre: "ことば遊び", question: "『カメラ』の中にかくれている生きものは?", acceptableAnswers: ["かめ", "カメ"], hint: "「か」から はじまる 2もじの ことばだよ", displayAnswer: "カメ", note: "『カメ・ラ』のはじめに『カメ』があります。", openEnded: false },
  { no: 147, genre: "ことば遊び", question: "『カバン』の中にかくれている動物は?", acceptableAnswers: ["かば", "カバ"], hint: "「か」から はじまる 2もじの ことばだよ", displayAnswer: "カバ", note: "『カバ・ン』のはじめに『カバ』があります。", openEnded: false },
  { no: 148, genre: "ことば遊び", question: "『すいか』の中にかくれている海の生きものは?", acceptableAnswers: ["いか"], hint: "「い」から はじまる 2もじの ことばだよ", displayAnswer: "いか", note: "『す・いか』の中に『いか』があります。", openEnded: false },
  { no: 149, genre: "ことば遊び", question: "『たいこ』の中にかくれている魚は?", acceptableAnswers: ["たい"], hint: "「た」から はじまる 2もじの ことばだよ", displayAnswer: "たい", note: "『たい・こ』のはじめに『たい』があります。", openEnded: false },
  { no: 150, genre: "ことば遊び", question: "『あくま』の中にかくれている動物は?", acceptableAnswers: ["くま"], hint: "「く」から はじまる 2もじの ことばだよ", displayAnswer: "くま", note: "『あ・くま』の中に『くま』があります。", openEnded: false },
  { no: 151, genre: "ことば遊び", question: "『はちみつ』の中にかくれている虫は?", acceptableAnswers: ["はち"], hint: "「は」から はじまる 2もじの ことばだよ", displayAnswer: "はち", note: "『はち・みつ』のはじめに『はち』があります。", openEnded: false },
  { no: 152, genre: "ことば遊び", question: "『かるい』を後ろから読むと出てくる海の動物は?", acceptableAnswers: ["いるか", "イルカ"], hint: "「い」から はじまる 3もじの ことばだよ", displayAnswer: "イルカ", note: "『か・る・い』を逆に読むと『い・る・か』です。", openEnded: false },
  { no: 153, genre: "ことば遊び", question: "上から読んでも下から読んでも同じ名前になる、赤い野菜は?", acceptableAnswers: ["とまと", "トマト"], hint: "「と」から はじまる 3もじの ことばだよ", displayAnswer: "トマト", note: "『ト・マ・ト』は逆から読んでも同じです。", openEnded: false },
  { no: 154, genre: "ことば遊び", question: "上から読んでも下から読んでも同じになる、ニュースがのっている紙は?", acceptableAnswers: ["しんぶんし"], hint: "「し」から はじまる 5もじの ことばだよ", displayAnswer: "しんぶんし", note: "『し・ん・ぶ・ん・し』は逆から読んでも同じです。", openEnded: false },
  { no: 155, genre: "ことば遊び", question: "『たからばこ』から『た』をぬくと、どんな箱になる?", acceptableAnswers: ["あきばこ", "からばこ", "空箱"], hint: "「あ」から はじまる 4もじの ことばだよ", displayAnswer: "からばこ(空箱)", note: "『た』を取ると『からばこ』になります。", openEnded: false },
  { no: 156, genre: "ことば遊び", question: "『イス』の前に『ス』をつけると、どこの国になる?", acceptableAnswers: ["すいす", "スイス"], hint: "「す」から はじまる 3もじの ことばだよ", displayAnswer: "スイス", note: "『ス』+『イス』で『スイス』です。", openEnded: false },
  { no: 157, genre: "ことば遊び", question: "お父さんが『いやだ!』と言いそうな果物は?", acceptableAnswers: ["ぱぱいや", "パパイヤ"], hint: "「ぱ」から はじまる 4もじの ことばだよ", displayAnswer: "パパイヤ", note: "『パパ、いや』と聞こえる言葉遊びです。", openEnded: false },
  { no: 158, genre: "ことば遊び", question: "アリが10匹集まると、どんなあいさつになる?", acceptableAnswers: ["ありがとう"], hint: "「あ」から はじまる 5もじの ことばだよ", displayAnswer: "ありがとう", note: "『アリが十(とう)』で『ありがとう』です。", openEnded: false },
  { no: 159, genre: "ことば遊び", question: "食べものをほめるとき、名前を呼ばれた気がする動物は?", acceptableAnswers: ["うま"], hint: "「う」から はじまる 2もじの ことばだよ", displayAnswer: "うま", note: "『うまい!』のはじめが『うま』です。", openEnded: false },
  { no: 160, genre: "ことば遊び", question: "いつも『まあ、いいか』と言っていそうな海の生きものは?", acceptableAnswers: ["いか"], hint: "「い」から はじまる 2もじの ことばだよ", displayAnswer: "いか", note: "『まあ、いいか』の終わりが『いか』です。", openEnded: false },
  { no: 161, genre: "数字・かたち", question: "角が3つ、辺も3本。おにぎりにもよくある形は?", acceptableAnswers: ["さんかくけい", "さんかっけい", "三角形"], hint: "「さ」から はじまる 6もじの ことばだよ", displayAnswer: "三角形", note: "3つの角と3本の辺をもつ形です。", openEnded: false },
  { no: 162, genre: "数字・かたち", question: "角が1つもなく、どこまで進んでもぐるりともとの場所へ戻る形は?", acceptableAnswers: ["えん", "まる", "円"], hint: "「え」から はじまる 2もじの ことばだよ", displayAnswer: "円(まる)", note: "円には角がありません。", openEnded: false },
  { no: 163, genre: "数字・かたち", question: "4本の辺が同じ長さで、角も4つある形は?", acceptableAnswers: ["せいほうけい", "正方形"], hint: "「せ」から はじまる 6もじの ことばだよ", displayAnswer: "正方形", note: "4辺が同じ長さで、4つの角は直角です。", openEnded: false },
  { no: 164, genre: "数字・かたち", question: "立っていると数字、横に寝ると『ずっと続く』しるしに見える数字は?", acceptableAnswers: ["8", "はち", "はちつ", "やっつ"], hint: "「8」から はじまる 1もじの ことばだよ", displayAnswer: "8", note: "8を横にすると無限を表す『∞』に似ています。", openEnded: false },
  { no: 165, genre: "数字・かたち", question: "逆さまにすると6になる数字は?", acceptableAnswers: ["9", "きゅう", "ここのつ"], hint: "「9」から はじまる 1もじの ことばだよ", displayAnswer: "9", note: "9を上下逆にすると6の形に見えます。", openEnded: false },
  { no: 166, genre: "数字・かたち", question: "10の半分はいくつ?", acceptableAnswers: ["5", "いつつ", "ご"], hint: "「5」から はじまる 1もじの ことばだよ", displayAnswer: "5", note: "10を2つに同じだけ分けると5です。", openEnded: false },
  { no: 167, genre: "数字・かたち", question: "えんぴつ1ダースは何本?", acceptableAnswers: ["12", "12ほん", "12本", "じゅうにほん"], hint: "「1」から はじまる 2もじの ことばだよ", displayAnswer: "12本", note: "1ダースは12個のことです。", openEnded: false },
  { no: 168, genre: "数字・かたち", question: "1週間は7日。では、2週間は何日?", acceptableAnswers: ["14", "14にち", "14日", "じゅうよっか"], hint: "「1」から はじまる 2もじの ことばだよ", displayAnswer: "14日", note: "7日+7日で14日です。", openEnded: false },
  { no: 169, genre: "数字・かたち", question: "1年のうち、28日ある月はいくつ?", acceptableAnswers: ["12", "12かげつ", "12かげつぜんぶ", "12か月全部", "じゅうにかげつ", "ぜんぶ"], hint: "「1」から はじまる 2もじの ことばだよ", displayAnswer: "12か月全部", note: "どの月にも少なくとも28日はあります。", openEnded: false },
  { no: 170, genre: "数字・かたち", question: "鉄1キログラムと、わた1キログラム。重いのはどっち?", acceptableAnswers: ["いっしょ", "おなじ", "おなじおもさ", "同じ重さ"], hint: "「お」から はじまる 3もじの ことばだよ", displayAnswer: "同じ重さ", note: "どちらも1キログラムです。", openEnded: false },
  { no: 171, genre: "数字・かたち", question: "テーブルにりんごが3個あります。そこから2個もらいました。あなたが持っているのはいくつ?", acceptableAnswers: ["2", "2こ", "2個", "にこ"], hint: "「2」から はじまる 1もじの ことばだよ", displayAnswer: "2個", note: "もらった2個を持っています。", openEnded: false },
  { no: 172, genre: "数字・かたち", question: "枝に鳥が5羽。1羽が飛んでいきました。枝に残った鳥は何羽?", acceptableAnswers: ["4", "4わ", "4羽", "よんわ"], hint: "「4」から はじまる 1もじの ことばだよ", displayAnswer: "4羽", note: "5羽から1羽が飛んだので4羽です。", openEnded: false },
  { no: 173, genre: "数字・かたち", question: "あめが10個。5人に2個ずつ配ると、残りはいくつ?", acceptableAnswers: ["0", "0こ", "0個", "ぜろ", "ぜろこ", "れいこ"], hint: "「0」から はじまる 1もじの ことばだよ", displayAnswer: "0個", note: "2個×5人で10個すべて配ります。", openEnded: false },
  { no: 174, genre: "数字・かたち", question: "かけっこで2番の人を追いこしました。今、自分は何番?", acceptableAnswers: ["2", "2ばん", "2番", "にばん"], hint: "「2」から はじまる 1もじの ことばだよ", displayAnswer: "2番", note: "2番の人の場所に入るので、自分が2番です。", openEnded: false },
  { no: 175, genre: "数字・かたち", question: "3匹のねこが3分で3匹のねずみをつかまえます。同じ速さなら、1匹のねこが1匹をつかまえるのは何分?", acceptableAnswers: ["3", "3ふん", "3分", "さんぷん"], hint: "「3」から はじまる 1もじの ことばだよ", displayAnswer: "3分", note: "ねこ1匹が3分で1匹をつかまえる計算です。", openEnded: false },
  { no: 176, genre: "数字・かたち", question: "四角い部屋の4つの角に、ねこが1匹ずついます。どのねこからも、ほかの3匹が見えます。ねこは全部で何匹?", acceptableAnswers: ["4", "4ひき", "4匹", "よんひき"], hint: "「4」から はじまる 1もじの ことばだよ", displayAnswer: "4匹", note: "それぞれの角に1匹ずつなので4匹です。", openEnded: false },
  { no: 177, genre: "数字・かたち", question: "お父さんが2人、息子が2人います。でも、全部で3人しかいません。どういう3人?", acceptableAnswers: ["おじいさん", "おとうさん", "そふ", "そふ・ちち・むすこ", "ちち", "むすこ", "むすこさん", "息子", "父", "祖父", "祖父・父・息子"], hint: "「そ」から はじまる 2もじの ことばだよ", displayAnswer: "祖父・父・息子", note: "父は『祖父の息子』でもあり、『息子の父』でもあります。", openEnded: false },
  { no: 178, genre: "数字・かたち", question: "1人と1人がいっしょになって、しばらくすると3人になることがあります。どんなとき?", acceptableAnswers: ["かぞくにあかちゃんがうまれたとき", "家族に赤ちゃんが生まれたとき"], hint: "よーく かんがえてみてね。わかったら「こたえを みる」を おしてね", displayAnswer: "家族に赤ちゃんが生まれたとき", note: "2人の家族に赤ちゃんが加わると3人です。", openEnded: true },
  { no: 179, genre: "数字・かたち", question: "時計が3時に3回鳴ります。では、6時には何回鳴る?", acceptableAnswers: ["6", "6かい", "6回", "ろっかい"], hint: "「6」から はじまる 1もじの ことばだよ", displayAnswer: "6回", note: "時刻の数だけ鳴る時計なら6回です。", openEnded: false },
  { no: 180, genre: "数字・かたち", question: "曜日の名前を使わずに、続いている3日を言ってください。", acceptableAnswers: ["あした", "きのう", "きのう・きょう・あした", "きょう"], hint: "「あ」から はじまる 3もじの ことばだよ", displayAnswer: "きのう・きょう・あした", note: "3日が順番に続いています。", openEnded: false },
  { no: 181, genre: "ひらめき", question: "暗い部屋に、ろうそく・ランプ・ストーブがあります。マッチを1本だけ持って入ったら、最初に何をつける?", acceptableAnswers: ["まっち", "マッチ"], hint: "「ま」から はじまる 2もじの ことばだよ", displayAnswer: "マッチ", note: "ほかのものに火をつける前に、まずマッチをつけます。", openEnded: false },
  { no: 182, genre: "ひらめき", question: "人や物をぬらさないために使うのに、自分は使うほどぬれていくものは?", acceptableAnswers: ["たおる", "タオル"], hint: "「た」から はじまる 3もじの ことばだよ", displayAnswer: "タオル", note: "水分をふき取るので、タオル自身はぬれます。", openEnded: false },
  { no: 183, genre: "ひらめき", question: "土から取れば取るほど、大きくなるものは?", acceptableAnswers: ["あな", "穴"], hint: "「あ」から はじまる 2もじの ことばだよ", displayAnswer: "穴", note: "土を取りのぞくほど穴が広がります。", openEnded: false },
  { no: 184, genre: "ひらめき", question: "投げることはできないのに、『ひく』ことができるものは?", acceptableAnswers: ["かぜ", "風邪"], hint: "「か」から はじまる 2もじの ことばだよ", displayAnswer: "かぜ(風邪)", note: "風邪は『ひく』と言いますが、投げるとは言いません。", openEnded: false },
  { no: 185, genre: "ひらめき", question: "毎年1つずつ増えるのに、決して減らないものは?", acceptableAnswers: ["ねんれい", "年れい"], hint: "「ね」から はじまる 4もじの ことばだよ", displayAnswer: "年れい", note: "年を重ねるたびに年齢は増えます。", openEnded: false },
  { no: 186, genre: "ひらめき", question: "封筒のすみから動かないのに、世界中を旅できるものは?", acceptableAnswers: ["きって", "切手"], hint: "「き」から はじまる 2もじの ことばだよ", displayAnswer: "切手", note: "封筒のすみについたまま、手紙といっしょに旅します。", openEnded: false },
  { no: 187, genre: "ひらめき", question: "かぎがたくさんあるのに、ドアを1つも開けられないものは?", acceptableAnswers: ["きーぼーど", "キーボード"], hint: "「き」から はじまる 5もじの ことばだよ", displayAnswer: "キーボード", note: "ボタンを『キー』といいます。", openEnded: false },
  { no: 188, genre: "ひらめき", question: "自分のものなのに、自分よりほかの人のほうがよく使うものは?", acceptableAnswers: ["じぶんのなまえ", "自分の名前"], hint: "「じ」から はじまる 7もじの ことばだよ", displayAnswer: "自分の名前", note: "ほかの人があなたを呼ぶときによく使います。", openEnded: false },
  { no: 189, genre: "ひらめき", question: "穴がたくさんあいているのに、水をしっかり吸いこむものは?", acceptableAnswers: ["すぽんじ", "スポンジ"], hint: "「す」から はじまる 4もじの ことばだよ", displayAnswer: "スポンジ", note: "細かな穴に水をたくわえます。", openEnded: false },
  { no: 190, genre: "ひらめき", question: "その名前を声に出したとたん、こわれてしまうものは?", acceptableAnswers: ["しずけさ", "静けさ"], hint: "「し」から はじまる 4もじの ことばだよ", displayAnswer: "静けさ", note: "声を出すと静かではなくなります。", openEnded: false },
  { no: 191, genre: "ひらめき", question: "いつもやって来ると言われるのに、来たときには別の名前になる日は?", acceptableAnswers: ["あした"], hint: "「あ」から はじまる 3もじの ことばだよ", displayAnswer: "あした", note: "あしたが来ると、その日は『きょう』になります。", openEnded: false },
  { no: 192, genre: "ひらめき", question: "ガラスをこわさずに通りぬけ、部屋を明るくするものは?", acceptableAnswers: ["ひかり", "光"], hint: "「ひ」から はじまる 3もじの ことばだよ", displayAnswer: "光", note: "透明なガラスは光を通します。", openEnded: false },
  { no: 193, genre: "ひらめき", question: "首があるのに頭はなく、腕があるのに手はないものは?", acceptableAnswers: ["しゃつ", "シャツ"], hint: "「し」から はじまる 2もじの ことばだよ", displayAnswer: "シャツ", note: "服の『首まわり』と『そで(腕)』を人の体にたとえています。", openEnded: false },
  { no: 194, genre: "ひらめき", question: "町はあるのに家はなく、川はあるのに水がないものは?", acceptableAnswers: ["ちず", "地図"], hint: "「ち」から はじまる 2もじの ことばだよ", displayAnswer: "地図", note: "地図には町や川が記号や線でかかれています。", openEnded: false },
  { no: 195, genre: "ひらめき", question: "箱には入れにくいのに、パンを焼くと部屋いっぱいに広がるものは?", acceptableAnswers: ["におい"], hint: "「に」から はじまる 3もじの ことばだよ", displayAnswer: "におい", note: "においは空気中に広がります。", openEnded: false },
  { no: 196, genre: "ひらめき", question: "頭としっぽがあるのに、体がない丸いものは?", acceptableAnswers: ["こいん", "コイン"], hint: "「こ」から はじまる 3もじの ことばだよ", displayAnswer: "コイン", note: "コインの表裏を英語で『ヘッド』『テール』と呼ぶ言い方があります。", openEnded: false },
  { no: 197, genre: "ひらめき", question: "船を止めたいとき海へ投げ、進みたいとき引き上げる重いものは?", acceptableAnswers: ["いかり"], hint: "「い」から はじまる 3もじの ことばだよ", displayAnswer: "いかり", note: "海底に下ろして船が流されにくくします。", openEnded: false },
  { no: 198, genre: "ひらめき", question: "大雨の中を、ぼうしもかさもなしで歩いたのに、髪の毛が1本もぬれなかった人がいます。なぜ?", acceptableAnswers: ["そのにんにはかみのけがなかったから", "その人には髪の毛がなかったから"], hint: "よーく かんがえてみてね。わかったら「こたえを みる」を おしてね", displayAnswer: "その人には髪の毛がなかったから", note: "髪の毛がなければ、髪はぬれません。", openEnded: true },
  { no: 199, genre: "ひらめき", question: "富士山が見つかる前、日本でいちばん高かった山は?", acceptableAnswers: ["ふじさん", "富士山"], hint: "「ふ」から はじまる 4もじの ことばだよ", displayAnswer: "富士山", note: "見つかる前から富士山の高さは変わりません。", openEnded: false },
  { no: 200, genre: "ひらめき", question: "本当にそうしている間は『はい』と答えられない質問は?", acceptableAnswers: ["『いま、ねむっていますか?』", "『今、眠っていますか?』"], hint: "よーく かんがえてみてね。わかったら「こたえを みる」を おしてね", displayAnswer: "『今、眠っていますか?』", note: "眠っている最中は返事ができません。", openEnded: true },
];

export const NAZONAZO_GENRES = [
  "食べもの",
  "どうぶつ",
  "自然・季節",
  "家の中・身の回り",
  "学校・文房具",
  "町・乗りもの",
  "からだ",
  "ことば遊び",
  "数字・かたち",
  "ひらめき",
] as const;
